/* Simulation code for MultFive generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */
#define time data->localData[0]->timeValue

/* States */
#define _$P$dummy(i) data->localData[i]->realVars[0]
#define _$P$PRE$P$dummy(i) $P$PRE$P$dummy
#define $P$dummy _$P$dummy(0)
#define $P$PRE$P$dummy data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$P$dummy data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$P$dummy $P$ATTRIBUTE$P$dummy
#define $P$dummy__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$P$dummy__varInfo data->modelData.realVarsData[0].info

/* StatesDerivatives */
#define _$P$DER$P$dummy(i) data->localData[i]->realVars[1]
#define _$P$PRE$P$DER$P$dummy(i) $P$PRE$P$DER$P$dummy
#define $P$DER$P$dummy _$P$DER$P$dummy(0)
#define $P$PRE$P$DER$P$dummy data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$P$DER$P$dummy data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$P$dummy $P$ATTRIBUTE$P$DER$P$dummy
#define $P$DER$P$dummy__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$P$DER$P$dummy__varInfo data->modelData.realVarsData[1].info

/* Algebraic Vars */
#define _$POutput(i) data->localData[i]->realVars[2]
#define _$P$PRE$POutput(i) $P$PRE$POutput
#define $POutput _$POutput(0)
#define $P$PRE$POutput data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$POutput data->modelData.realVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$POutput $P$ATTRIBUTE$POutput
#define $POutput__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$POutput__varInfo data->modelData.realVarsData[2].info
#define _$PInput(i) data->localData[i]->realVars[3]
#define _$P$PRE$PInput(i) $P$PRE$PInput
#define $PInput _$PInput(0)
#define $P$PRE$PInput data->simulationInfo.realVarsPre[3]
#define $P$ATTRIBUTE$PInput data->modelData.realVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PInput $P$ATTRIBUTE$PInput
#define $PInput__varInfo data->modelData.realVarsData[3].info
#define $P$PRE$PInput__varInfo data->modelData.realVarsData[3].info

/* Nonlinear Constraints For Optimization */

/* InlineSolver Vars */

/* Algebraic Parameter */

/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */

/* Algebraic Boolean Vars */

/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */


