/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for MultFive generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MultFive_functions.h"
#include "MultFive_model.h"
#include "MultFive_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void MultFive_function_initSample(DATA *data)
{
  long i=0;

}

const char *MultFive_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  *out_EquationIndexes = NULL;
  return "empty";
}

int MultFive_function_ZeroCrossings(DATA *data, double *gout, double *t)
{

  
  return 0;
}

const char *MultFive_relationDescription(int i)
{
  return "empty";
}

int MultFive_function_updateRelations(DATA *data, int evalforZeroCross)
{
  
  if(evalforZeroCross)
  {
  }
  else
  {
  }
  
  return 0;
}

int MultFive_checkForDiscreteChanges(DATA *data)
{
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes");
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  return needToIterate;
}


