/* Initialization */
/* Simulation code for MultFive generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MultFive_functions.h"
#include "MultFive_model.h"
#include "MultFive_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "MultFive_11mix.h"
#include "MultFive_12jac.h"

const char *MultFive_initialResidualDescription(int i)
{
  return "empty";
}

int MultFive_initial_residual(DATA *data, double *initialResiduals)
{
  const int *equationIndexes = NULL;
  int i = 0;
  
  infoStreamPrint(LOG_RES_INIT, 1, "updating initial residuals");
  if (ACTIVE_STREAM(LOG_RES_INIT)) messageClose(LOG_RES_INIT);
  
  return 0;
}

/*
 equation index: 1
 type: SIMPLE_ASSIGN
 Output = 5.0 * Input
 */
void MultFive_eqFunction_1(DATA *data)
{
  const int equationIndexes[2] = {1,1};
  $POutput = (5.0 * $PInput);
}


int MultFive_functionInitialEquations(DATA *data)
{

  data->simulationInfo.discreteCall = 1;
  MultFive_eqFunction_1(data);
  data->simulationInfo.discreteCall = 0;
  
  return 0;
}

/* funtion initialize mixed systems */
void MultFive_initialMixedSystem(MIXED_SYSTEM_DATA* mixedSystemData)
{
  /* initial mixed systems */
  /* inline mixed systems */
  /* parameter mixed systems */
  /* model mixed systems */
  /* jacobians mixed systems */
}


