/* Jacobians */
/* Simulation code for MultFive generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MultFive_functions.h"
#include "MultFive_model.h"
#include "MultFive_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "MultFive_12jac.h"
int MultFive_initialAnalyticJacobianG(void* inData)
{
  return 1;
}
int MultFive_initialAnalyticJacobianA(void* inData)
{
  return 1;
}
int MultFive_initialAnalyticJacobianB(void* inData)
{
  return 1;
}
int MultFive_initialAnalyticJacobianC(void* inData)
{
  return 1;
}
int MultFive_initialAnalyticJacobianD(void* inData)
{
  return 1;
}

int MultFive_functionJacG_column(void* data)
{
  return 0;
}
int MultFive_functionJacA_column(void* inData)
{
  DATA* data = ((DATA*)inData);
  int index = MultFive_INDEX_JAC_A;
  return 0;
}
int MultFive_functionJacB_column(void* data)
{
  return 0;
}
int MultFive_functionJacC_column(void* data)
{
  return 0;
}
int MultFive_functionJacD_column(void* data)
{
  return 0;
}


