/* Simulation code for HelloWorld.Hello generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */
#define time data->localData[0]->timeValue

/* States */
#define _$Px(i) data->localData[i]->realVars[0]
#define _$P$PRE$Px(i) $P$PRE$Px
#define $Px _$Px(0)
#define $P$PRE$Px data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$Px data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Px $P$ATTRIBUTE$Px
#define $Px__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$Px__varInfo data->modelData.realVarsData[0].info

/* StatesDerivatives */
#define _$P$DER$Px(i) data->localData[i]->realVars[1]
#define _$P$PRE$P$DER$Px(i) $P$PRE$P$DER$Px
#define $P$DER$Px _$P$DER$Px(0)
#define $P$PRE$P$DER$Px data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$P$DER$Px data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Px $P$ATTRIBUTE$P$DER$Px
#define $P$DER$Px__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$P$DER$Px__varInfo data->modelData.realVarsData[1].info

/* Algebraic Vars */

/* Nonlinear Constraints For Optimization */

/* InlineSolver Vars */

/* Algebraic Parameter */
#define $Pa data->simulationInfo.realParameter[0]
#define _$Pa(i) $Pa
#define $P$ATTRIBUTE$Pa data->modelData.realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Pa $P$ATTRIBUTE$Pa
#define $Pa__varInfo data->modelData.realParameterData[0].info

/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */

/* Algebraic Boolean Vars */

/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */


