/* Main Simulation File */
/* Simulation code for HelloWorld.test generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HelloWorld.test_functions.h"
#include "HelloWorld.test_model.h"
#include "HelloWorld.test_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#define prefixedName_performSimulation HelloWorld_test_performSimulation
#include <simulation/solver/perform_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#ifdef __cplusplus
extern "C" {
#endif
#ifdef _OMC_MEASURE_TIME
int measure_time_flag = 1;
#else
int measure_time_flag = 0;
#endif

int HelloWorld_test_input_function(DATA *data)
{
  return 0;
}

int HelloWorld_test_input_function_init(DATA *data)
{
  return 0;
}

int HelloWorld_test_output_function(DATA *data)
{
  return 0;
}


/*
 equation index: 3
 type: SIMPLE_ASSIGN
 der(Hello1._x) = (-Hello1.a) * Hello1.x
 */
void HelloWorld_test_eqFunction_3(DATA *data)
{
  const int equationIndexes[2] = {1,3};
  $P$DER$PHello1$Px = ((-$PHello1$Pa) * $PHello1$Px);
}


int HelloWorld_test_functionDAE(DATA *data)
{
  data->simulationInfo.needToIterate = 0;
  data->simulationInfo.discreteCall = 1;
  HelloWorld_test_eqFunction_3(data);
  
  return 0;
}


/* forwarded equations */
extern void HelloWorld_test_eqFunction_3(DATA* data);

static void functionODE_system0(DATA *data)
{
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(3);
  #endif
  HelloWorld_test_eqFunction_3(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(3);
  #endif
}

int HelloWorld_test_functionODE(DATA *data)
{
#ifdef _OMC_MEASURE_TIME
  rt_tick(SIM_TIMER_FUNCTION_ODE);
#endif

  
  data->simulationInfo.discreteCall = 0;
  functionODE_system0(data);
#ifdef _OMC_MEASURE_TIME
  rt_accumulate(SIM_TIMER_FUNCTION_ODE);
#endif

  return 0;
}

#include <simulation/solver/simulation_inline_solver.h>
const char *_omc_force_solver=_OMC_FORCE_SOLVER;
const int inline_work_states_ndims=_OMC_SOLVER_WORK_STATES_NDIMS;
int HelloWorld_test_functionODE_inline(DATA* data, double stepSize)
{
  return 0;
}

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data);

#include "HelloWorld.test_12jac.h"
#include "HelloWorld.test_13opt.h"
extern void HelloWorld_test_callExternalObjectConstructors(DATA *data);
extern void HelloWorld_test_callExternalObjectDestructors(DATA *_data);
extern void HelloWorld_test_initialNonLinearSystem(NONLINEAR_SYSTEM_DATA *data);
extern void HelloWorld_test_initialLinearSystem(LINEAR_SYSTEM_DATA *data);
extern void HelloWorld_test_initialMixedSystem(MIXED_SYSTEM_DATA *data);
extern void HelloWorld_test_initializeStateSets(STATE_SET_DATA* statesetData, DATA *data);
extern int HelloWorld_test_functionAlgebraics(DATA *data);
extern int HelloWorld_test_function_storeDelayed(DATA *data);
extern int HelloWorld_test_updateBoundVariableAttributes(DATA *data);
extern const char* HelloWorld_test_initialResidualDescription(int);
extern int HelloWorld_test_initial_residual(DATA *data, double* initialResiduals);
extern int HelloWorld_test_functionInitialEquations(DATA *data);
extern int HelloWorld_test_updateBoundParameters(DATA *data);
extern int HelloWorld_test_checkForAsserts(DATA *data);
extern int HelloWorld_test_function_ZeroCrossings(DATA *data, double* gout, double* t);
extern int HelloWorld_test_function_updateRelations(DATA *data, int evalZeroCross);
extern int HelloWorld_test_checkForDiscreteChanges(DATA *data);
extern const char* HelloWorld_test_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* HelloWorld_test_relationDescription(int i);
extern void HelloWorld_test_function_initSample(DATA *data);
extern int HelloWorld_test_initialAnalyticJacobianG(void* data);
extern int HelloWorld_test_initialAnalyticJacobianA(void* data);
extern int HelloWorld_test_initialAnalyticJacobianB(void* data);
extern int HelloWorld_test_initialAnalyticJacobianC(void* data);
extern int HelloWorld_test_initialAnalyticJacobianD(void* data);
extern int HelloWorld_test_functionJacG_column(void* data);
extern int HelloWorld_test_functionJacA_column(void* data);
extern int HelloWorld_test_functionJacB_column(void* data);
extern int HelloWorld_test_functionJacC_column(void* data);
extern int HelloWorld_test_functionJacD_column(void* data);
extern const char* HelloWorld_test_linear_model_frame(void);
extern int HelloWorld_test_mayer(DATA* data, modelica_real* res);
extern int HelloWorld_test_lagrange(DATA* data, modelica_real* res);
extern int HelloWorld_test_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);

struct OpenModelicaGeneratedFunctionCallbacks HelloWorld_test_callback = {
   (int (*)(DATA *, void *)) HelloWorld_test_performSimulation,
   HelloWorld_test_callExternalObjectConstructors,
   HelloWorld_test_callExternalObjectDestructors,
   HelloWorld_test_initialNonLinearSystem,
   HelloWorld_test_initialLinearSystem,
   HelloWorld_test_initialMixedSystem,
   HelloWorld_test_initializeStateSets,
   HelloWorld_test_functionODE,
   HelloWorld_test_functionAlgebraics,
   HelloWorld_test_functionDAE,
   HelloWorld_test_input_function,
   HelloWorld_test_input_function_init,
   HelloWorld_test_output_function,
   HelloWorld_test_function_storeDelayed,
   HelloWorld_test_functionODE_inline,
   HelloWorld_test_updateBoundVariableAttributes,
   HelloWorld_test_initialResidualDescription,
   HelloWorld_test_initial_residual,
   1 /* useSymbolicInitialization */,
   0 /* useHomotopy */,
   HelloWorld_test_functionInitialEquations,
   HelloWorld_test_updateBoundParameters,
   HelloWorld_test_checkForAsserts,
   HelloWorld_test_function_ZeroCrossings,
   HelloWorld_test_function_updateRelations,
   HelloWorld_test_checkForDiscreteChanges,
   HelloWorld_test_zeroCrossingDescription,
   HelloWorld_test_relationDescription,
   HelloWorld_test_function_initSample,
   HelloWorld_test_INDEX_JAC_G,
   HelloWorld_test_INDEX_JAC_A,
   HelloWorld_test_INDEX_JAC_B,
   HelloWorld_test_INDEX_JAC_C,
   HelloWorld_test_INDEX_JAC_D,
   HelloWorld_test_initialAnalyticJacobianG,
   HelloWorld_test_initialAnalyticJacobianA,
   HelloWorld_test_initialAnalyticJacobianB,
   HelloWorld_test_initialAnalyticJacobianC,
   HelloWorld_test_initialAnalyticJacobianD,
   HelloWorld_test_functionJacG_column,
   HelloWorld_test_functionJacA_column,
   HelloWorld_test_functionJacB_column,
   HelloWorld_test_functionJacC_column,
   HelloWorld_test_functionJacD_column,
   HelloWorld_test_linear_model_frame,
   HelloWorld_test_mayer,
   HelloWorld_test_lagrange,
   HelloWorld_test_pickUpBoundsForInputsInOptimization

};

void HelloWorld_test_setupDataStruc(DATA *data)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &HelloWorld_test_callback;
  data->modelData.modelName = "HelloWorld.test";
  data->modelData.modelFilePrefix = "HelloWorld.test";
  data->modelData.modelDir = "";
  data->modelData.modelGUID = "{fa621ced-4860-4b92-92a9-9ede48c2c186}";
  #ifdef OPENMODELICA_XML_FROM_FILE_AT_RUNTIME
  data->modelData.initXMLData = NULL;
  data->modelData.modelDataXml.infoXMLData = NULL;
  #else
  data->modelData.initXMLData =
  #include "HelloWorld.test_init.c"
  ;
  data->modelData.modelDataXml.infoXMLData =
  #include "HelloWorld.test_info.c"
  ;
  #endif
  
  data->modelData.nStates = 1;
  data->modelData.nVariablesReal = 2*1+0+0;
  data->modelData.nDiscreteReal = 0;
  data->modelData.nVariablesInteger = 0;
  data->modelData.nVariablesBoolean = 0;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 1;
  data->modelData.nParametersInteger = 0;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 0;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  data->modelData.nJacobians = 5;
  
  data->modelData.nAliasReal = 0;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 0;
  data->modelData.nSamples = 0;
  data->modelData.nRelations = 0;
  data->modelData.nMathEvents = 0;
  data->modelData.nInitEquations = 0;
  data->modelData.nInitAlgorithms = 0;
  data->modelData.nInitResiduals = 0;    /* data->modelData.nInitEquations + data->modelData.nInitAlgorithms */
  data->modelData.nExtObjs = 0;
  data->modelData.modelDataXml.fileName = "HelloWorld.test_info.xml";
  data->modelData.modelDataXml.nFunctions = 0;
  data->modelData.modelDataXml.nProfileBlocks = 0;
  data->modelData.modelDataXml.nEquations = 4;
  data->modelData.nMixedSystems = 0;
  data->modelData.nLinearSystems = 0;
  data->modelData.nNonLinearSystems = 0;
  data->modelData.nStateSets = 0;
  data->modelData.nInlineVars = 0;
  data->modelData.nOptimizeConstraints = 0;
  
  data->modelData.nDelayExpressions = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA simulation_data;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    HelloWorld_test_setupDataStruc(&simulation_data);
    simulation_data.threadData = threadData;
    res = _main_SimulationRuntime(argc, argv, &simulation_data);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

