/* Simulation code for HelloWorld.test generated by the OpenModelica Compiler 1.9.1 Beta4 (r22666) (RML version). */
#define time data->localData[0]->timeValue

/* States */
/* Hello1.x */
#define _$PHello1$Px(i) data->localData[i]->realVars[0]
#define $PHello1$Px _$PHello1$Px(0)
#define $P$PRE$PHello1$Px data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$PHello1$Px data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PHello1$Px $P$ATTRIBUTE$PHello1$Px
#define $PHello1$Px__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$PHello1$Px__varInfo data->modelData.realVarsData[0].info
#define _$P$PRE$PHello1$Px(i) $P$PRE$PHello1$Px


/* StatesDerivatives */
/* der(Hello1.x) */
#define _$P$DER$PHello1$Px(i) data->localData[i]->realVars[1]
#define $P$DER$PHello1$Px _$P$DER$PHello1$Px(0)
#define $P$PRE$P$DER$PHello1$Px data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$P$DER$PHello1$Px data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PHello1$Px $P$ATTRIBUTE$P$DER$PHello1$Px
#define $P$DER$PHello1$Px__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$P$DER$PHello1$Px__varInfo data->modelData.realVarsData[1].info
#define _$P$PRE$P$DER$PHello1$Px(i) $P$PRE$P$DER$PHello1$Px


/* Non Discrete Real Algebraic Vars */

/* Discrete Real Algebraic Vars */

/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Algebraic Parameter */
/* Hello1.a */
#define $PHello1$Pa data->simulationInfo.realParameter[0]
#define _$PHello1$Pa(i) $PHello1$Pa
#define $P$ATTRIBUTE$PHello1$Pa data->modelData.realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PHello1$Pa $P$ATTRIBUTE$PHello1$Pa
#define $PHello1$Pa__varInfo data->modelData.realParameterData[0].info


/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */

/* Algebraic Boolean Vars */

/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */


