/* Initialization */
/* Simulation code for HelloWorld.test generated by the OpenModelica Compiler 1.9.1 Beta4 (r22666) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HelloWorld.test_functions.h"
#include "HelloWorld.test_model.h"
#include "HelloWorld.test_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "HelloWorld.test_11mix.h"
#include "HelloWorld.test_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif

const char *HelloWorld_test_initialResidualDescription(int i)
{
  return "empty";
}

int HelloWorld_test_initial_residual(DATA *data, double *initialResiduals)
{
  const int *equationIndexes = NULL;
  int i = 0;
  
  infoStreamPrint(LOG_RES_INIT, 1, "updating initial residuals");
  if (ACTIVE_STREAM(LOG_RES_INIT)) messageClose(LOG_RES_INIT);
  
  return 0;
}

/*
 equation index: 1
 type: SIMPLE_ASSIGN
 Hello1._x = $_start(Hello1.x)
 */
void HelloWorld_test_eqFunction_1(DATA *data)
{
  const int equationIndexes[2] = {1,1};
  TRACE_PUSH
  $PHello1$Px = $P$ATTRIBUTE$PHello1$Px.start;
  TRACE_POP
}
/*
 equation index: 2
 type: SIMPLE_ASSIGN
 der(Hello1._x) = (-Hello1.a) * Hello1.x
 */
void HelloWorld_test_eqFunction_2(DATA *data)
{
  const int equationIndexes[2] = {1,2};
  TRACE_PUSH
  $P$DER$PHello1$Px = ((-$PHello1$Pa) * $PHello1$Px);
  TRACE_POP
}


int HelloWorld_test_functionInitialEquations(DATA *data)
{

  data->simulationInfo.discreteCall = 1;
  HelloWorld_test_eqFunction_1(data);

  HelloWorld_test_eqFunction_2(data);
  data->simulationInfo.discreteCall = 0;
  
  return 0;
}
int HelloWorld_test_functionRemovedInitialEquations(DATA *data)
{
  const int *equationIndexes = NULL;
  double res = 0.0;

  
  return 0;
}

/* funtion initialize mixed systems */
void HelloWorld_test_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA* mixedSystemData)
{
  /* initial mixed systems */
  /* parameter mixed systems */
  /* model mixed systems */
  /* jacobians mixed systems */
}

#if defined(__cplusplus)
}
#endif

