# Makefile generated by OpenModelica

# Simulations use -O3 by default
SIM_OR_DYNLOAD_OPT_LEVEL=
CC=gcc
CXX=g++
LINK=g++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE= 
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS=-I"C:/OpenModelica1.9.1Beta2//include/omc/c" -I.  -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME
LDFLAGS= -L"C:/OpenModelica1.9.1Beta2//lib/omc" -L"C:/OpenModelica1.9.1Beta2//lib" -Wl,--stack,0x2000000,-rpath,"C:/OpenModelica1.9.1Beta2//lib/omc" -Wl,-rpath,"C:/OpenModelica1.9.1Beta2//lib"  -lregex -lexpat -lgc -lpthread -fopenmp -loleaut32  -lSimulationRuntimeC -lgc -lexpat -lregex -static-libgcc -luuid -loleaut32 -lole32 -lws2_32 -lsundials_kinsol -lsundials_nvecserial -lipopt -lcoinmumps -lcoinmetis -lpthread -lm -lgfortranbegin -lgfortran -lmingw32 -lgcc_eh -lmoldname -lmingwex -lmsvcrt -luser32 -lkernel32 -ladvapi32 -lshell32 -llapack-mingw -ltmglib-mingw -lblas-mingw -lf2c -linteractive -lwsock32 -llis -lstdc++
MAINFILE=HelloWorld.test.c
MAINOBJ=HelloWorld.test.o
CFILES=HelloWorld.test_functions.c HelloWorld.test_records.c \
HelloWorld.test_01exo.c HelloWorld.test_02nls.c HelloWorld.test_03lsy.c HelloWorld.test_04set.c HelloWorld.test_05evt.c HelloWorld.test_06inz.c HelloWorld.test_07dly.c \
HelloWorld.test_08bnd.c HelloWorld.test_09alg.c HelloWorld.test_10asr.c HelloWorld.test_11mix.c HelloWorld.test_12jac.c HelloWorld.test_13opt.c HelloWorld.test_14lnz.c
OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) HelloWorld.test.makefile HelloWorld.test_literals.h HelloWorld.test_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that HelloWorld.test_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) HelloWorld.test_functions.h HelloWorld.test_literals.h $(OFILES)
	$(CC) -I. -o HelloWorld.test$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS)    $(CFLAGS) $(LDFLAGS)
clean:
	@rm -f HelloWorld.test_records.o $(MAINOBJ)

bundle:
	@tar -cvf HelloWorld.test_Files.tar $(GENERATEDFILES)