/* Linearization */
/* Simulation code for MultFive generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MultFive_functions.h"
#include "MultFive_model.h"
#include "MultFive_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


const char *MultFive_linear_model_frame()
{
  return "model linear_MultFive\n  parameter Integer n = 1; // states \n  parameter Integer k = 1; // top-level inputs \n  parameter Integer l = 1; // top-level outputs \n"
  "  parameter Real x0[1] = {%s};\n"
  "  parameter Real u0[1] = {%s};\n"
  "  parameter Real A[1,1] = [%s];\n"
  "  parameter Real B[1,1] = [%s];\n"
  "  parameter Real C[1,1] = [%s];\n"
  "  parameter Real D[1,1] = [%s];\n"
  "  Real x[1](start=x0);\n"
  "  input Real u[1](start= u0);\n"
  "  output Real y[1];\n"
  "\n  Real x_P$dummy = x[1];\n    Real u_PInput = u[1];\n    Real y_POutput = y[1];\n  \n"
  "equation\n  der(x) = A * x + B * u;\n  y = C * x + D * u;\nend linear_MultFive;\n";
}


