/* External objects file */
/* Simulation code for ICSolar.ICS_Skeleton generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "ICSolar.ICS_Skeleton_functions.h"
#include "ICSolar.ICS_Skeleton_model.h"
#include "ICSolar.ICS_Skeleton_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


/* Has to be performed after _init.xml file has been read */
void ICSolar_ICS_Skeleton_callExternalObjectConstructors(DATA *data)
{
  real_array tmp2392;
  integer_array tmp2393;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2394;
  real_array tmp2395;
  integer_array tmp2396;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2397;
  real_array tmp2398;
  integer_array tmp2399;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2400;
  real_array tmp2401;
  integer_array tmp2402;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2403;
  real_array tmp2404;
  integer_array tmp2405;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2406;
  real_array tmp2407;
  integer_array tmp2408;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2409;
  real_array tmp2410;
  integer_array tmp2411;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2412;
  real_array tmp2413;
  integer_array tmp2414;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2415;
  real_array tmp2416;
  integer_array tmp2417;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2418;
  real_array tmp2419;
  integer_array tmp2420;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2421;
  real_array tmp2422;
  integer_array tmp2423;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2424;
  real_array tmp2425;
  integer_array tmp2426;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2427;
  real_array tmp2428;
  integer_array tmp2429;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2430;
  real_array tmp2431;
  integer_array tmp2432;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2433;
  real_array tmp2434;
  integer_array tmp2435;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2436;
  real_array tmp2437;
  integer_array tmp2438;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2439;
  real_array tmp2440;
  integer_array tmp2441;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2442;
  real_array tmp2443;
  integer_array tmp2444;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2445;
  real_array tmp2446;
  integer_array tmp2447;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2448;
  real_array tmp2449;
  integer_array tmp2450;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2451;
  real_array tmp2452;
  integer_array tmp2453;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2454;
  real_array tmp2455;
  integer_array tmp2456;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2457;
  real_array tmp2458;
  integer_array tmp2459;
  Modelica_Blocks_Types_ExternalCombiTable1D_constructor_rettype tmp2460;
  real_array tmp2461;
  integer_array tmp2462;
  Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_rettype tmp2463;
  /* data->simulationInfo.extObjs = NULL; */
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors");
  alloc_real_array(&tmp2392, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2393, 24, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13, (modelica_integer)(modelica_integer) 14, (modelica_integer)(modelica_integer) 15, (modelica_integer)(modelica_integer) 16, (modelica_integer)(modelica_integer) 17, (modelica_integer)(modelica_integer) 18, (modelica_integer)(modelica_integer) 19, (modelica_integer)(modelica_integer) 20, (modelica_integer)(modelica_integer) 21, (modelica_integer)(modelica_integer) 22, (modelica_integer)(modelica_integer) 23, (modelica_integer)(modelica_integer) 24, (modelica_integer)(modelica_integer) 25);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2394 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "DNI_THTFin_vdot", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\20150323\\measuredData20150323r1.txt", tmp2392, 0.0, tmp2393, 1, 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $PIC_Data_all$PtableID = tmp2394.c1;
  alloc_real_array(&tmp2395, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2396, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2397 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2395, 0.0, tmp2396, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PtableID = tmp2397.c1;
  alloc_real_array(&tmp2398, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2399, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2400 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2398, tmp2399, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2400.c1;
  alloc_real_array(&tmp2401, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2402, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2403 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2401, 0.0, tmp2402, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PtableID = tmp2403.c1;
  alloc_real_array(&tmp2404, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2405, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2406 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2404, tmp2405, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2406.c1;
  alloc_real_array(&tmp2407, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2408, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2409 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2407, 0.0, tmp2408, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PtableID = tmp2409.c1;
  alloc_real_array(&tmp2410, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2411, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2412 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2410, tmp2411, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2412.c1;
  alloc_real_array(&tmp2413, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2414, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2415 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2413, 0.0, tmp2414, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PtableID = tmp2415.c1;
  alloc_real_array(&tmp2416, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2417, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2418 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2416, tmp2417, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2418.c1;
  alloc_real_array(&tmp2419, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2420, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2421 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2419, 0.0, tmp2420, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PtableID = tmp2421.c1;
  alloc_real_array(&tmp2422, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2423, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2424 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2422, tmp2423, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2424.c1;
  alloc_real_array(&tmp2425, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2426, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2427 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2425, 0.0, tmp2426, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PtableID = tmp2427.c1;
  alloc_real_array(&tmp2428, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2429, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2430 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2428, tmp2429, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2430.c1;
  alloc_real_array(&tmp2431, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2432, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2433 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2431, 0.0, tmp2432, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PtableID = tmp2433.c1;
  alloc_real_array(&tmp2434, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2435, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2436 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2434, tmp2435, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2436.c1;
  alloc_real_array(&tmp2437, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2438, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2439 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2437, 0.0, tmp2438, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PtableID = tmp2439.c1;
  alloc_real_array(&tmp2440, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2441, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2442 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2440, tmp2441, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2442.c1;
  alloc_real_array(&tmp2443, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2444, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2445 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2443, 0.0, tmp2444, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PtableID = tmp2445.c1;
  alloc_real_array(&tmp2446, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2447, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2448 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2446, tmp2447, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2448.c1;
  alloc_real_array(&tmp2449, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2450, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2451 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2449, 0.0, tmp2450, 3, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PtableID = tmp2451.c1;
  alloc_real_array(&tmp2452, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2453, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2454 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2452, tmp2453, 1);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pshadingfraction_function1$PLUT$PtableID = tmp2454.c1;
  alloc_real_array(&tmp2455, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2456, 4, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2457 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "tab1", "C:/Users/kenton.phillips/Documents/GitHub/RPI_CASE_ICS_Modelica/weatherdata/USA_NY_New.York-LaGuardia.AP.725030_TMY3.mos", tmp2455, tmp2456, 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_context1$PweaDat$PdatRea1$PtableID = tmp2457.c1;
  alloc_real_array(&tmp2458, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2459, 25, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13, (modelica_integer)(modelica_integer) 14, (modelica_integer)(modelica_integer) 15, (modelica_integer)(modelica_integer) 16, (modelica_integer)(modelica_integer) 17, (modelica_integer)(modelica_integer) 18, (modelica_integer)(modelica_integer) 19, (modelica_integer)(modelica_integer) 20, (modelica_integer)(modelica_integer) 21, (modelica_integer)(modelica_integer) 22, (modelica_integer)(modelica_integer) 23, (modelica_integer)(modelica_integer) 24, (modelica_integer)(modelica_integer) 25, (modelica_integer)(modelica_integer) 26, (modelica_integer)(modelica_integer) 27, (modelica_integer)(modelica_integer) 28, (modelica_integer)(modelica_integer) 29, (modelica_integer)(modelica_integer) 30);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  tmp2460 = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "tab1", "C:/Users/kenton.phillips/Documents/GitHub/RPI_CASE_ICS_Modelica/weatherdata/USA_NY_New.York-LaGuardia.AP.725030_TMY3.mos", tmp2458, tmp2459, 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index);
  #endif
  $Pics_context1$PweaDat$PdatRea$PtableID = tmp2460.c1;
  alloc_real_array(&tmp2461, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2462, 1, (modelica_integer)(modelica_integer) 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  tmp2463 = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "T_Cav", "C:\\Users\\kenton.phillips\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\20150323\\T_Cav_data.txt", tmp2461, 0.0, tmp2462, 1, 2);

  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index);
  #endif
  $PT_cav_in$PtableID = tmp2463.c1;
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors finished");
}

void ICSolar_ICS_Skeleton_callExternalObjectDestructors(DATA *data)
{
  if(data->simulationInfo.extObjs)
  {
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$PIC_Data_all$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_context1$PweaDat$PdatRea1$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_context1$PweaDat$PdatRea$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$PT_cav_in$PtableID);
    free(data->simulationInfo.extObjs);
    data->simulationInfo.extObjs = 0;
  }
}

