/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for ICSolar.ICS_Skeleton generated by the OpenModelica Compiler 1.9.1 (r22929) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "ICSolar.ICS_Skeleton_functions.h"
#include "ICSolar.ICS_Skeleton_model.h"
#include "ICSolar.ICS_Skeleton_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void ICSolar_ICS_Skeleton_function_initSample(DATA *data)
{
  long i=0;
}

const char *ICSolar_ICS_Skeleton_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time >= pre(T_cav_in.nextTimeEvent)",
  "abs(ics_envelopecassette1.Tubing[1].flowPort_b.H_flow) - ics_envelopecassette1.flowport_a.H_flow < 0.0",
  "ics_envelopecassette1.Power_Electric < 0.0",
  "(1.0 - ics_envelopecassette1.glazingLossesOuter.R_sfc / cos(ics_context1.AOI)) * (1.0 - ics_envelopecassette1.glazingLossesOuter.c_disp * 6.0 / cos(ics_context1.AOI)) * (1.0 + -2.0 * ics_envelopecassette1.glazingLossesOuter.R_Fres / (1.0 + ics_envelopecassette1.glazingLossesOuter.R_Fres)) < 0.0",
  "G_DN <= 1.0",
  "ics_context1.AOI <= 1.570795",
  "ics_context1.DNI > 0.0",
  "ics_context1.weaDat.conTim1.simTim - pre(ics_context1.weaDat.conTim1.tStart) > 31536000.0",
  "ics_context1.weaDat.conTim.simTim - pre(ics_context1.weaDat.conTim.tStart) > 31536000.0",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[1].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[2].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[3].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[4].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[5].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[6].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[7].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[8].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[9].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[10].eGen_on.nextTimeEvent)",
  "time >= pre(IC_Data_all.nextTimeEvent)",
  "integer(ics_context1.weaDat.conTim1.simTim / 31536000.0, 0)",
  "integer(ics_context1.weaDat.conTim.simTim / 31536000.0, 1)"};
  static const int occurEqs0[] = {1,3850};
  static const int occurEqs1[] = {1,3850};
  static const int occurEqs2[] = {1,4845};
  static const int occurEqs3[] = {1,4681};
  static const int occurEqs4[] = {1,4846};
  static const int occurEqs5[] = {1,4683};
  static const int occurEqs6[] = {1,4684};
  static const int occurEqs7[] = {1,4556};
  static const int occurEqs8[] = {1,4573};
  static const int occurEqs9[] = {1,3862};
  static const int occurEqs10[] = {1,3861};
  static const int occurEqs11[] = {1,3860};
  static const int occurEqs12[] = {1,3859};
  static const int occurEqs13[] = {1,3858};
  static const int occurEqs14[] = {1,3857};
  static const int occurEqs15[] = {1,3856};
  static const int occurEqs16[] = {1,3855};
  static const int occurEqs17[] = {1,3854};
  static const int occurEqs18[] = {1,3853};
  static const int occurEqs19[] = {1,4665};
  static const int occurEqs20[] = {1,3851};
  static const int occurEqs21[] = {1,3852};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3,occurEqs4,occurEqs5,occurEqs6,occurEqs7,occurEqs8,occurEqs9,occurEqs10,occurEqs11,occurEqs12,occurEqs13,occurEqs14,occurEqs15,occurEqs16,occurEqs17,occurEqs18,occurEqs19,occurEqs20,occurEqs21};
  *out_EquationIndexes = (int*) occurEqs[i];
  return res[i];
}

int ICSolar_ICS_Skeleton_function_ZeroCrossingsEquations(DATA *data)
{
  
  TRACE_PUSH
  data->simulationInfo.callStatistics.functionZeroCrossingsEquations++;
  
  data->simulationInfo.discreteCall = 0;
  ICSolar_ICS_Skeleton_eqFunction_3850(data);

  ICSolar_ICS_Skeleton_eqFunction_3853(data);

  ICSolar_ICS_Skeleton_eqFunction_3854(data);

  ICSolar_ICS_Skeleton_eqFunction_3855(data);

  ICSolar_ICS_Skeleton_eqFunction_3856(data);

  ICSolar_ICS_Skeleton_eqFunction_3857(data);

  ICSolar_ICS_Skeleton_eqFunction_3858(data);

  ICSolar_ICS_Skeleton_eqFunction_3859(data);

  ICSolar_ICS_Skeleton_eqFunction_3860(data);

  ICSolar_ICS_Skeleton_eqFunction_3861(data);

  ICSolar_ICS_Skeleton_eqFunction_3862(data);

  ICSolar_ICS_Skeleton_eqFunction_3863(data);

  ICSolar_ICS_Skeleton_eqFunction_3866(data);

  ICSolar_ICS_Skeleton_eqFunction_3868(data);

  ICSolar_ICS_Skeleton_eqFunction_3869(data);

  ICSolar_ICS_Skeleton_eqFunction_3870(data);

  ICSolar_ICS_Skeleton_eqFunction_3871(data);

  ICSolar_ICS_Skeleton_eqFunction_3872(data);

  ICSolar_ICS_Skeleton_eqFunction_3874(data);

  ICSolar_ICS_Skeleton_eqFunction_3880(data);

  ICSolar_ICS_Skeleton_eqFunction_3890(data);

  ICSolar_ICS_Skeleton_eqFunction_3891(data);

  ICSolar_ICS_Skeleton_eqFunction_3892(data);

  ICSolar_ICS_Skeleton_eqFunction_3893(data);

  ICSolar_ICS_Skeleton_eqFunction_3895(data);

  ICSolar_ICS_Skeleton_eqFunction_3896(data);

  ICSolar_ICS_Skeleton_eqFunction_3897(data);

  ICSolar_ICS_Skeleton_eqFunction_3898(data);

  ICSolar_ICS_Skeleton_eqFunction_3902(data);

  ICSolar_ICS_Skeleton_eqFunction_3903(data);

  ICSolar_ICS_Skeleton_eqFunction_3904(data);

  ICSolar_ICS_Skeleton_eqFunction_3905(data);

  ICSolar_ICS_Skeleton_eqFunction_3906(data);

  ICSolar_ICS_Skeleton_eqFunction_3907(data);

  ICSolar_ICS_Skeleton_eqFunction_3908(data);

  ICSolar_ICS_Skeleton_eqFunction_3909(data);

  ICSolar_ICS_Skeleton_eqFunction_3910(data);

  ICSolar_ICS_Skeleton_eqFunction_3911(data);

  ICSolar_ICS_Skeleton_eqFunction_3912(data);

  ICSolar_ICS_Skeleton_eqFunction_3913(data);

  ICSolar_ICS_Skeleton_eqFunction_3914(data);

  ICSolar_ICS_Skeleton_eqFunction_3922(data);

  ICSolar_ICS_Skeleton_eqFunction_3926(data);

  ICSolar_ICS_Skeleton_eqFunction_3936(data);

  ICSolar_ICS_Skeleton_eqFunction_3937(data);

  ICSolar_ICS_Skeleton_eqFunction_3938(data);

  ICSolar_ICS_Skeleton_eqFunction_3939(data);

  ICSolar_ICS_Skeleton_eqFunction_3941(data);

  ICSolar_ICS_Skeleton_eqFunction_3942(data);

  ICSolar_ICS_Skeleton_eqFunction_3943(data);

  ICSolar_ICS_Skeleton_eqFunction_3944(data);

  ICSolar_ICS_Skeleton_eqFunction_3945(data);

  ICSolar_ICS_Skeleton_eqFunction_3946(data);

  ICSolar_ICS_Skeleton_eqFunction_3947(data);

  ICSolar_ICS_Skeleton_eqFunction_3963(data);

  ICSolar_ICS_Skeleton_eqFunction_3964(data);

  ICSolar_ICS_Skeleton_eqFunction_3965(data);

  ICSolar_ICS_Skeleton_eqFunction_3966(data);

  ICSolar_ICS_Skeleton_eqFunction_3967(data);

  ICSolar_ICS_Skeleton_eqFunction_3968(data);

  ICSolar_ICS_Skeleton_eqFunction_3969(data);

  ICSolar_ICS_Skeleton_eqFunction_3970(data);

  ICSolar_ICS_Skeleton_eqFunction_3971(data);

  ICSolar_ICS_Skeleton_eqFunction_3972(data);

  ICSolar_ICS_Skeleton_eqFunction_3973(data);

  ICSolar_ICS_Skeleton_eqFunction_3974(data);

  ICSolar_ICS_Skeleton_eqFunction_3975(data);

  ICSolar_ICS_Skeleton_eqFunction_3976(data);

  ICSolar_ICS_Skeleton_eqFunction_3977(data);

  ICSolar_ICS_Skeleton_eqFunction_3978(data);

  ICSolar_ICS_Skeleton_eqFunction_3986(data);

  ICSolar_ICS_Skeleton_eqFunction_3990(data);

  ICSolar_ICS_Skeleton_eqFunction_4000(data);

  ICSolar_ICS_Skeleton_eqFunction_4001(data);

  ICSolar_ICS_Skeleton_eqFunction_4002(data);

  ICSolar_ICS_Skeleton_eqFunction_4003(data);

  ICSolar_ICS_Skeleton_eqFunction_4005(data);

  ICSolar_ICS_Skeleton_eqFunction_4006(data);

  ICSolar_ICS_Skeleton_eqFunction_4007(data);

  ICSolar_ICS_Skeleton_eqFunction_4008(data);

  ICSolar_ICS_Skeleton_eqFunction_4009(data);

  ICSolar_ICS_Skeleton_eqFunction_4010(data);

  ICSolar_ICS_Skeleton_eqFunction_4011(data);

  ICSolar_ICS_Skeleton_eqFunction_4027(data);

  ICSolar_ICS_Skeleton_eqFunction_4028(data);

  ICSolar_ICS_Skeleton_eqFunction_4029(data);

  ICSolar_ICS_Skeleton_eqFunction_4030(data);

  ICSolar_ICS_Skeleton_eqFunction_4031(data);

  ICSolar_ICS_Skeleton_eqFunction_4032(data);

  ICSolar_ICS_Skeleton_eqFunction_4033(data);

  ICSolar_ICS_Skeleton_eqFunction_4034(data);

  ICSolar_ICS_Skeleton_eqFunction_4035(data);

  ICSolar_ICS_Skeleton_eqFunction_4036(data);

  ICSolar_ICS_Skeleton_eqFunction_4037(data);

  ICSolar_ICS_Skeleton_eqFunction_4038(data);

  ICSolar_ICS_Skeleton_eqFunction_4039(data);

  ICSolar_ICS_Skeleton_eqFunction_4040(data);

  ICSolar_ICS_Skeleton_eqFunction_4041(data);

  ICSolar_ICS_Skeleton_eqFunction_4042(data);

  ICSolar_ICS_Skeleton_eqFunction_4050(data);

  ICSolar_ICS_Skeleton_eqFunction_4054(data);

  ICSolar_ICS_Skeleton_eqFunction_4064(data);

  ICSolar_ICS_Skeleton_eqFunction_4065(data);

  ICSolar_ICS_Skeleton_eqFunction_4066(data);

  ICSolar_ICS_Skeleton_eqFunction_4067(data);

  ICSolar_ICS_Skeleton_eqFunction_4069(data);

  ICSolar_ICS_Skeleton_eqFunction_4070(data);

  ICSolar_ICS_Skeleton_eqFunction_4071(data);

  ICSolar_ICS_Skeleton_eqFunction_4072(data);

  ICSolar_ICS_Skeleton_eqFunction_4073(data);

  ICSolar_ICS_Skeleton_eqFunction_4074(data);

  ICSolar_ICS_Skeleton_eqFunction_4075(data);

  ICSolar_ICS_Skeleton_eqFunction_4090(data);

  ICSolar_ICS_Skeleton_eqFunction_4091(data);

  ICSolar_ICS_Skeleton_eqFunction_4092(data);

  ICSolar_ICS_Skeleton_eqFunction_4093(data);

  ICSolar_ICS_Skeleton_eqFunction_4094(data);

  ICSolar_ICS_Skeleton_eqFunction_4095(data);

  ICSolar_ICS_Skeleton_eqFunction_4096(data);

  ICSolar_ICS_Skeleton_eqFunction_4097(data);

  ICSolar_ICS_Skeleton_eqFunction_4098(data);

  ICSolar_ICS_Skeleton_eqFunction_4099(data);

  ICSolar_ICS_Skeleton_eqFunction_4100(data);

  ICSolar_ICS_Skeleton_eqFunction_4101(data);

  ICSolar_ICS_Skeleton_eqFunction_4102(data);

  ICSolar_ICS_Skeleton_eqFunction_4103(data);

  ICSolar_ICS_Skeleton_eqFunction_4104(data);

  ICSolar_ICS_Skeleton_eqFunction_4105(data);

  ICSolar_ICS_Skeleton_eqFunction_4113(data);

  ICSolar_ICS_Skeleton_eqFunction_4117(data);

  ICSolar_ICS_Skeleton_eqFunction_4127(data);

  ICSolar_ICS_Skeleton_eqFunction_4128(data);

  ICSolar_ICS_Skeleton_eqFunction_4129(data);

  ICSolar_ICS_Skeleton_eqFunction_4130(data);

  ICSolar_ICS_Skeleton_eqFunction_4132(data);

  ICSolar_ICS_Skeleton_eqFunction_4133(data);

  ICSolar_ICS_Skeleton_eqFunction_4134(data);

  ICSolar_ICS_Skeleton_eqFunction_4135(data);

  ICSolar_ICS_Skeleton_eqFunction_4136(data);

  ICSolar_ICS_Skeleton_eqFunction_4137(data);

  ICSolar_ICS_Skeleton_eqFunction_4138(data);

  ICSolar_ICS_Skeleton_eqFunction_4154(data);

  ICSolar_ICS_Skeleton_eqFunction_4155(data);

  ICSolar_ICS_Skeleton_eqFunction_4156(data);

  ICSolar_ICS_Skeleton_eqFunction_4157(data);

  ICSolar_ICS_Skeleton_eqFunction_4158(data);

  ICSolar_ICS_Skeleton_eqFunction_4159(data);

  ICSolar_ICS_Skeleton_eqFunction_4160(data);

  ICSolar_ICS_Skeleton_eqFunction_4161(data);

  ICSolar_ICS_Skeleton_eqFunction_4162(data);

  ICSolar_ICS_Skeleton_eqFunction_4163(data);

  ICSolar_ICS_Skeleton_eqFunction_4164(data);

  ICSolar_ICS_Skeleton_eqFunction_4165(data);

  ICSolar_ICS_Skeleton_eqFunction_4166(data);

  ICSolar_ICS_Skeleton_eqFunction_4167(data);

  ICSolar_ICS_Skeleton_eqFunction_4168(data);

  ICSolar_ICS_Skeleton_eqFunction_4169(data);

  ICSolar_ICS_Skeleton_eqFunction_4177(data);

  ICSolar_ICS_Skeleton_eqFunction_4181(data);

  ICSolar_ICS_Skeleton_eqFunction_4191(data);

  ICSolar_ICS_Skeleton_eqFunction_4192(data);

  ICSolar_ICS_Skeleton_eqFunction_4193(data);

  ICSolar_ICS_Skeleton_eqFunction_4194(data);

  ICSolar_ICS_Skeleton_eqFunction_4196(data);

  ICSolar_ICS_Skeleton_eqFunction_4197(data);

  ICSolar_ICS_Skeleton_eqFunction_4198(data);

  ICSolar_ICS_Skeleton_eqFunction_4199(data);

  ICSolar_ICS_Skeleton_eqFunction_4200(data);

  ICSolar_ICS_Skeleton_eqFunction_4201(data);

  ICSolar_ICS_Skeleton_eqFunction_4202(data);

  ICSolar_ICS_Skeleton_eqFunction_4218(data);

  ICSolar_ICS_Skeleton_eqFunction_4219(data);

  ICSolar_ICS_Skeleton_eqFunction_4220(data);

  ICSolar_ICS_Skeleton_eqFunction_4221(data);

  ICSolar_ICS_Skeleton_eqFunction_4222(data);

  ICSolar_ICS_Skeleton_eqFunction_4223(data);

  ICSolar_ICS_Skeleton_eqFunction_4224(data);

  ICSolar_ICS_Skeleton_eqFunction_4225(data);

  ICSolar_ICS_Skeleton_eqFunction_4226(data);

  ICSolar_ICS_Skeleton_eqFunction_4227(data);

  ICSolar_ICS_Skeleton_eqFunction_4228(data);

  ICSolar_ICS_Skeleton_eqFunction_4229(data);

  ICSolar_ICS_Skeleton_eqFunction_4230(data);

  ICSolar_ICS_Skeleton_eqFunction_4231(data);

  ICSolar_ICS_Skeleton_eqFunction_4232(data);

  ICSolar_ICS_Skeleton_eqFunction_4233(data);

  ICSolar_ICS_Skeleton_eqFunction_4241(data);

  ICSolar_ICS_Skeleton_eqFunction_4245(data);

  ICSolar_ICS_Skeleton_eqFunction_4255(data);

  ICSolar_ICS_Skeleton_eqFunction_4256(data);

  ICSolar_ICS_Skeleton_eqFunction_4257(data);

  ICSolar_ICS_Skeleton_eqFunction_4258(data);

  ICSolar_ICS_Skeleton_eqFunction_4260(data);

  ICSolar_ICS_Skeleton_eqFunction_4261(data);

  ICSolar_ICS_Skeleton_eqFunction_4262(data);

  ICSolar_ICS_Skeleton_eqFunction_4263(data);

  ICSolar_ICS_Skeleton_eqFunction_4264(data);

  ICSolar_ICS_Skeleton_eqFunction_4265(data);

  ICSolar_ICS_Skeleton_eqFunction_4266(data);

  ICSolar_ICS_Skeleton_eqFunction_4282(data);

  ICSolar_ICS_Skeleton_eqFunction_4283(data);

  ICSolar_ICS_Skeleton_eqFunction_4284(data);

  ICSolar_ICS_Skeleton_eqFunction_4285(data);

  ICSolar_ICS_Skeleton_eqFunction_4286(data);

  ICSolar_ICS_Skeleton_eqFunction_4287(data);

  ICSolar_ICS_Skeleton_eqFunction_4288(data);

  ICSolar_ICS_Skeleton_eqFunction_4289(data);

  ICSolar_ICS_Skeleton_eqFunction_4290(data);

  ICSolar_ICS_Skeleton_eqFunction_4291(data);

  ICSolar_ICS_Skeleton_eqFunction_4292(data);

  ICSolar_ICS_Skeleton_eqFunction_4293(data);

  ICSolar_ICS_Skeleton_eqFunction_4294(data);

  ICSolar_ICS_Skeleton_eqFunction_4295(data);

  ICSolar_ICS_Skeleton_eqFunction_4296(data);

  ICSolar_ICS_Skeleton_eqFunction_4297(data);

  ICSolar_ICS_Skeleton_eqFunction_4306(data);

  ICSolar_ICS_Skeleton_eqFunction_4310(data);

  ICSolar_ICS_Skeleton_eqFunction_4320(data);

  ICSolar_ICS_Skeleton_eqFunction_4321(data);

  ICSolar_ICS_Skeleton_eqFunction_4322(data);

  ICSolar_ICS_Skeleton_eqFunction_4323(data);

  ICSolar_ICS_Skeleton_eqFunction_4325(data);

  ICSolar_ICS_Skeleton_eqFunction_4326(data);

  ICSolar_ICS_Skeleton_eqFunction_4327(data);

  ICSolar_ICS_Skeleton_eqFunction_4328(data);

  ICSolar_ICS_Skeleton_eqFunction_4329(data);

  ICSolar_ICS_Skeleton_eqFunction_4330(data);

  ICSolar_ICS_Skeleton_eqFunction_4331(data);

  ICSolar_ICS_Skeleton_eqFunction_4347(data);

  ICSolar_ICS_Skeleton_eqFunction_4348(data);

  ICSolar_ICS_Skeleton_eqFunction_4349(data);

  ICSolar_ICS_Skeleton_eqFunction_4350(data);

  ICSolar_ICS_Skeleton_eqFunction_4351(data);

  ICSolar_ICS_Skeleton_eqFunction_4352(data);

  ICSolar_ICS_Skeleton_eqFunction_4353(data);

  ICSolar_ICS_Skeleton_eqFunction_4354(data);

  ICSolar_ICS_Skeleton_eqFunction_4355(data);

  ICSolar_ICS_Skeleton_eqFunction_4356(data);

  ICSolar_ICS_Skeleton_eqFunction_4357(data);

  ICSolar_ICS_Skeleton_eqFunction_4358(data);

  ICSolar_ICS_Skeleton_eqFunction_4359(data);

  ICSolar_ICS_Skeleton_eqFunction_4360(data);

  ICSolar_ICS_Skeleton_eqFunction_4361(data);

  ICSolar_ICS_Skeleton_eqFunction_4362(data);

  ICSolar_ICS_Skeleton_eqFunction_4370(data);

  ICSolar_ICS_Skeleton_eqFunction_4374(data);

  ICSolar_ICS_Skeleton_eqFunction_4384(data);

  ICSolar_ICS_Skeleton_eqFunction_4385(data);

  ICSolar_ICS_Skeleton_eqFunction_4386(data);

  ICSolar_ICS_Skeleton_eqFunction_4387(data);

  ICSolar_ICS_Skeleton_eqFunction_4389(data);

  ICSolar_ICS_Skeleton_eqFunction_4390(data);

  ICSolar_ICS_Skeleton_eqFunction_4391(data);

  ICSolar_ICS_Skeleton_eqFunction_4392(data);

  ICSolar_ICS_Skeleton_eqFunction_4393(data);

  ICSolar_ICS_Skeleton_eqFunction_4394(data);

  ICSolar_ICS_Skeleton_eqFunction_4395(data);

  ICSolar_ICS_Skeleton_eqFunction_4410(data);

  ICSolar_ICS_Skeleton_eqFunction_4411(data);

  ICSolar_ICS_Skeleton_eqFunction_4412(data);

  ICSolar_ICS_Skeleton_eqFunction_4413(data);

  ICSolar_ICS_Skeleton_eqFunction_4414(data);

  ICSolar_ICS_Skeleton_eqFunction_4415(data);

  ICSolar_ICS_Skeleton_eqFunction_4416(data);

  ICSolar_ICS_Skeleton_eqFunction_4417(data);

  ICSolar_ICS_Skeleton_eqFunction_4418(data);

  ICSolar_ICS_Skeleton_eqFunction_4419(data);

  ICSolar_ICS_Skeleton_eqFunction_4420(data);

  ICSolar_ICS_Skeleton_eqFunction_4421(data);

  ICSolar_ICS_Skeleton_eqFunction_4422(data);

  ICSolar_ICS_Skeleton_eqFunction_4423(data);

  ICSolar_ICS_Skeleton_eqFunction_4424(data);

  ICSolar_ICS_Skeleton_eqFunction_4425(data);

  ICSolar_ICS_Skeleton_eqFunction_4433(data);

  ICSolar_ICS_Skeleton_eqFunction_4437(data);

  ICSolar_ICS_Skeleton_eqFunction_4447(data);

  ICSolar_ICS_Skeleton_eqFunction_4448(data);

  ICSolar_ICS_Skeleton_eqFunction_4449(data);

  ICSolar_ICS_Skeleton_eqFunction_4450(data);

  ICSolar_ICS_Skeleton_eqFunction_4451(data);

  ICSolar_ICS_Skeleton_eqFunction_4452(data);

  ICSolar_ICS_Skeleton_eqFunction_4453(data);

  ICSolar_ICS_Skeleton_eqFunction_4454(data);

  ICSolar_ICS_Skeleton_eqFunction_4455(data);

  ICSolar_ICS_Skeleton_eqFunction_4456(data);

  ICSolar_ICS_Skeleton_eqFunction_4457(data);

  ICSolar_ICS_Skeleton_eqFunction_4458(data);

  ICSolar_ICS_Skeleton_eqFunction_4459(data);

  ICSolar_ICS_Skeleton_eqFunction_4460(data);

  ICSolar_ICS_Skeleton_eqFunction_4463(data);

  ICSolar_ICS_Skeleton_eqFunction_4464(data);

  ICSolar_ICS_Skeleton_eqFunction_4465(data);

  ICSolar_ICS_Skeleton_eqFunction_4466(data);

  ICSolar_ICS_Skeleton_eqFunction_4467(data);

  ICSolar_ICS_Skeleton_eqFunction_4468(data);

  ICSolar_ICS_Skeleton_eqFunction_4469(data);

  ICSolar_ICS_Skeleton_eqFunction_4485(data);

  ICSolar_ICS_Skeleton_eqFunction_4486(data);

  ICSolar_ICS_Skeleton_eqFunction_4487(data);

  ICSolar_ICS_Skeleton_eqFunction_4488(data);

  ICSolar_ICS_Skeleton_eqFunction_4489(data);

  ICSolar_ICS_Skeleton_eqFunction_4490(data);

  ICSolar_ICS_Skeleton_eqFunction_4491(data);

  ICSolar_ICS_Skeleton_eqFunction_4492(data);

  ICSolar_ICS_Skeleton_eqFunction_4508(data);

  ICSolar_ICS_Skeleton_eqFunction_4509(data);

  ICSolar_ICS_Skeleton_eqFunction_4510(data);

  ICSolar_ICS_Skeleton_eqFunction_4511(data);

  ICSolar_ICS_Skeleton_eqFunction_4512(data);

  ICSolar_ICS_Skeleton_eqFunction_4513(data);

  ICSolar_ICS_Skeleton_eqFunction_4514(data);

  ICSolar_ICS_Skeleton_eqFunction_4515(data);

  ICSolar_ICS_Skeleton_eqFunction_4516(data);

  ICSolar_ICS_Skeleton_eqFunction_4517(data);

  ICSolar_ICS_Skeleton_eqFunction_4518(data);

  ICSolar_ICS_Skeleton_eqFunction_4519(data);

  ICSolar_ICS_Skeleton_eqFunction_4520(data);

  ICSolar_ICS_Skeleton_eqFunction_4548(data);

  ICSolar_ICS_Skeleton_eqFunction_4549(data);

  ICSolar_ICS_Skeleton_eqFunction_4550(data);

  ICSolar_ICS_Skeleton_eqFunction_4551(data);

  ICSolar_ICS_Skeleton_eqFunction_4552(data);

  ICSolar_ICS_Skeleton_eqFunction_4553(data);

  ICSolar_ICS_Skeleton_eqFunction_4554(data);

  ICSolar_ICS_Skeleton_eqFunction_4555(data);

  ICSolar_ICS_Skeleton_eqFunction_4556(data);

  ICSolar_ICS_Skeleton_eqFunction_4558(data);

  ICSolar_ICS_Skeleton_eqFunction_4561(data);

  ICSolar_ICS_Skeleton_eqFunction_4563(data);

  ICSolar_ICS_Skeleton_eqFunction_4564(data);

  ICSolar_ICS_Skeleton_eqFunction_4566(data);

  ICSolar_ICS_Skeleton_eqFunction_4567(data);

  ICSolar_ICS_Skeleton_eqFunction_4571(data);

  ICSolar_ICS_Skeleton_eqFunction_4572(data);

  ICSolar_ICS_Skeleton_eqFunction_4573(data);

  ICSolar_ICS_Skeleton_eqFunction_4575(data);

  ICSolar_ICS_Skeleton_eqFunction_4576(data);

  ICSolar_ICS_Skeleton_eqFunction_4577(data);

  ICSolar_ICS_Skeleton_eqFunction_4578(data);

  ICSolar_ICS_Skeleton_eqFunction_4579(data);

  ICSolar_ICS_Skeleton_eqFunction_4580(data);

  ICSolar_ICS_Skeleton_eqFunction_4581(data);

  ICSolar_ICS_Skeleton_eqFunction_4582(data);

  ICSolar_ICS_Skeleton_eqFunction_4614(data);

  ICSolar_ICS_Skeleton_eqFunction_4643(data);

  ICSolar_ICS_Skeleton_eqFunction_4644(data);

  ICSolar_ICS_Skeleton_eqFunction_4645(data);

  ICSolar_ICS_Skeleton_eqFunction_4646(data);

  ICSolar_ICS_Skeleton_eqFunction_4647(data);

  ICSolar_ICS_Skeleton_eqFunction_4648(data);

  ICSolar_ICS_Skeleton_eqFunction_4649(data);

  ICSolar_ICS_Skeleton_eqFunction_4650(data);

  ICSolar_ICS_Skeleton_eqFunction_4651(data);

  ICSolar_ICS_Skeleton_eqFunction_4652(data);

  ICSolar_ICS_Skeleton_eqFunction_4653(data);

  ICSolar_ICS_Skeleton_eqFunction_4654(data);

  ICSolar_ICS_Skeleton_eqFunction_4655(data);

  ICSolar_ICS_Skeleton_eqFunction_4656(data);

  ICSolar_ICS_Skeleton_eqFunction_4657(data);

  ICSolar_ICS_Skeleton_eqFunction_4658(data);

  ICSolar_ICS_Skeleton_eqFunction_4659(data);

  ICSolar_ICS_Skeleton_eqFunction_4660(data);

  ICSolar_ICS_Skeleton_eqFunction_4661(data);

  ICSolar_ICS_Skeleton_eqFunction_4662(data);

  ICSolar_ICS_Skeleton_eqFunction_4663(data);

  ICSolar_ICS_Skeleton_eqFunction_4664(data);

  ICSolar_ICS_Skeleton_eqFunction_4665(data);

  ICSolar_ICS_Skeleton_eqFunction_4666(data);

  ICSolar_ICS_Skeleton_eqFunction_4667(data);

  ICSolar_ICS_Skeleton_eqFunction_4668(data);

  ICSolar_ICS_Skeleton_eqFunction_4669(data);

  ICSolar_ICS_Skeleton_eqFunction_4670(data);

  ICSolar_ICS_Skeleton_eqFunction_4671(data);

  ICSolar_ICS_Skeleton_eqFunction_4672(data);

  ICSolar_ICS_Skeleton_eqFunction_4673(data);

  ICSolar_ICS_Skeleton_eqFunction_4674(data);

  ICSolar_ICS_Skeleton_eqFunction_4675(data);

  ICSolar_ICS_Skeleton_eqFunction_4676(data);

  ICSolar_ICS_Skeleton_eqFunction_4677(data);

  ICSolar_ICS_Skeleton_eqFunction_4678(data);

  ICSolar_ICS_Skeleton_eqFunction_4679(data);

  ICSolar_ICS_Skeleton_eqFunction_4680(data);

  ICSolar_ICS_Skeleton_eqFunction_4681(data);

  ICSolar_ICS_Skeleton_eqFunction_4682(data);

  ICSolar_ICS_Skeleton_eqFunction_4683(data);

  ICSolar_ICS_Skeleton_eqFunction_4685(data);

  ICSolar_ICS_Skeleton_eqFunction_4686(data);

  ICSolar_ICS_Skeleton_eqFunction_4687(data);

  ICSolar_ICS_Skeleton_eqFunction_4696(data);

  ICSolar_ICS_Skeleton_eqFunction_4697(data);

  ICSolar_ICS_Skeleton_eqFunction_4698(data);

  ICSolar_ICS_Skeleton_eqFunction_4699(data);

  ICSolar_ICS_Skeleton_eqFunction_4700(data);

  ICSolar_ICS_Skeleton_eqFunction_4701(data);

  ICSolar_ICS_Skeleton_eqFunction_4702(data);

  ICSolar_ICS_Skeleton_eqFunction_4711(data);

  ICSolar_ICS_Skeleton_eqFunction_4712(data);

  ICSolar_ICS_Skeleton_eqFunction_4713(data);

  ICSolar_ICS_Skeleton_eqFunction_4714(data);

  ICSolar_ICS_Skeleton_eqFunction_4715(data);

  ICSolar_ICS_Skeleton_eqFunction_4716(data);

  ICSolar_ICS_Skeleton_eqFunction_4717(data);

  ICSolar_ICS_Skeleton_eqFunction_4726(data);

  ICSolar_ICS_Skeleton_eqFunction_4727(data);

  ICSolar_ICS_Skeleton_eqFunction_4728(data);

  ICSolar_ICS_Skeleton_eqFunction_4729(data);

  ICSolar_ICS_Skeleton_eqFunction_4730(data);

  ICSolar_ICS_Skeleton_eqFunction_4731(data);

  ICSolar_ICS_Skeleton_eqFunction_4732(data);

  ICSolar_ICS_Skeleton_eqFunction_4741(data);

  ICSolar_ICS_Skeleton_eqFunction_4742(data);

  ICSolar_ICS_Skeleton_eqFunction_4743(data);

  ICSolar_ICS_Skeleton_eqFunction_4744(data);

  ICSolar_ICS_Skeleton_eqFunction_4745(data);

  ICSolar_ICS_Skeleton_eqFunction_4746(data);

  ICSolar_ICS_Skeleton_eqFunction_4747(data);

  ICSolar_ICS_Skeleton_eqFunction_4756(data);

  ICSolar_ICS_Skeleton_eqFunction_4757(data);

  ICSolar_ICS_Skeleton_eqFunction_4758(data);

  ICSolar_ICS_Skeleton_eqFunction_4759(data);

  ICSolar_ICS_Skeleton_eqFunction_4760(data);

  ICSolar_ICS_Skeleton_eqFunction_4761(data);

  ICSolar_ICS_Skeleton_eqFunction_4762(data);

  ICSolar_ICS_Skeleton_eqFunction_4771(data);

  ICSolar_ICS_Skeleton_eqFunction_4772(data);

  ICSolar_ICS_Skeleton_eqFunction_4773(data);

  ICSolar_ICS_Skeleton_eqFunction_4774(data);

  ICSolar_ICS_Skeleton_eqFunction_4775(data);

  ICSolar_ICS_Skeleton_eqFunction_4776(data);

  ICSolar_ICS_Skeleton_eqFunction_4777(data);

  ICSolar_ICS_Skeleton_eqFunction_4786(data);

  ICSolar_ICS_Skeleton_eqFunction_4787(data);

  ICSolar_ICS_Skeleton_eqFunction_4788(data);

  ICSolar_ICS_Skeleton_eqFunction_4789(data);

  ICSolar_ICS_Skeleton_eqFunction_4790(data);

  ICSolar_ICS_Skeleton_eqFunction_4791(data);

  ICSolar_ICS_Skeleton_eqFunction_4792(data);

  ICSolar_ICS_Skeleton_eqFunction_4801(data);

  ICSolar_ICS_Skeleton_eqFunction_4802(data);

  ICSolar_ICS_Skeleton_eqFunction_4803(data);

  ICSolar_ICS_Skeleton_eqFunction_4804(data);

  ICSolar_ICS_Skeleton_eqFunction_4805(data);

  ICSolar_ICS_Skeleton_eqFunction_4806(data);

  ICSolar_ICS_Skeleton_eqFunction_4807(data);

  ICSolar_ICS_Skeleton_eqFunction_4816(data);

  ICSolar_ICS_Skeleton_eqFunction_4817(data);

  ICSolar_ICS_Skeleton_eqFunction_4818(data);

  ICSolar_ICS_Skeleton_eqFunction_4819(data);

  ICSolar_ICS_Skeleton_eqFunction_4820(data);

  ICSolar_ICS_Skeleton_eqFunction_4821(data);

  ICSolar_ICS_Skeleton_eqFunction_4822(data);

  ICSolar_ICS_Skeleton_eqFunction_4831(data);

  ICSolar_ICS_Skeleton_eqFunction_4832(data);

  ICSolar_ICS_Skeleton_eqFunction_4833(data);

  ICSolar_ICS_Skeleton_eqFunction_4834(data);

  ICSolar_ICS_Skeleton_eqFunction_4835(data);

  ICSolar_ICS_Skeleton_eqFunction_4836(data);

  ICSolar_ICS_Skeleton_eqFunction_4837(data);

  ICSolar_ICS_Skeleton_eqFunction_4838(data);

  ICSolar_ICS_Skeleton_eqFunction_4839(data);

  ICSolar_ICS_Skeleton_eqFunction_4840(data);

  ICSolar_ICS_Skeleton_eqFunction_4841(data);

  ICSolar_ICS_Skeleton_eqFunction_4842(data);

  ICSolar_ICS_Skeleton_eqFunction_4843(data);

  ICSolar_ICS_Skeleton_eqFunction_4844(data);

  ICSolar_ICS_Skeleton_eqFunction_4854(data);
  
  TRACE_POP
  return 0;
}

int ICSolar_ICS_Skeleton_function_ZeroCrossings(DATA *data, double *gout)
{
  modelica_boolean tmp2834;
  modelica_boolean tmp2835;
  modelica_boolean tmp2836;
  modelica_real tmp2837;
  modelica_real tmp2838;
  modelica_real tmp2839;
  modelica_boolean tmp2840;
  modelica_boolean tmp2841;
  modelica_boolean tmp2842;
  modelica_boolean tmp2843;
  modelica_boolean tmp2844;
  modelica_boolean tmp2845;
  modelica_boolean tmp2846;
  modelica_boolean tmp2847;
  modelica_boolean tmp2848;
  modelica_boolean tmp2849;
  modelica_boolean tmp2850;
  modelica_boolean tmp2851;
  modelica_boolean tmp2852;
  modelica_boolean tmp2853;
  modelica_boolean tmp2854;
  modelica_boolean tmp2855;
  modelica_boolean tmp2856;
  modelica_real tmp2857;
  modelica_real tmp2858;
  
  TRACE_PUSH
  data->simulationInfo.callStatistics.functionZeroCrossings++;
  
  tmp2834 = GreaterEqZC(time, $P$PRE$PT_cav_in$PnextTimeEvent, data->simulationInfo.storedRelations[0]);
  gout[0] = (tmp2834) ? 1 : -1;
  tmp2835 = LessZC((fabs($Pics_envelopecassette1$PTubing$lB1$rB$PflowPort_b$PH_flow) - $Pics_envelopecassette1$Pflowport_a$PH_flow), 0.0, data->simulationInfo.storedRelations[1]);
  gout[1] = (tmp2835) ? 1 : -1;
  tmp2836 = LessZC($Pics_envelopecassette1$PPower_Electric, 0.0, data->simulationInfo.storedRelations[2]);
  gout[2] = (tmp2836) ? 1 : -1;
  tmp2837 = cos($Pics_context1$PAOI);
  if (tmp2837 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_sfc / cos(ics_context1.AOI)");}
  tmp2838 = cos($Pics_context1$PAOI);
  if (tmp2838 == 0) {throwStreamPrint(threadData, "Division by zero %s", "6.0 / cos(ics_context1.AOI)");}
  tmp2839 = (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres);
  if (tmp2839 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_Fres / (1.0 + ics_envelopecassette1.glazingLossesOuter.R_Fres)");}
  tmp2840 = LessZC(((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$PR_sfc / cos($Pics_context1$PAOI))) * ((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$Pc_disp * (6.0 / cos($Pics_context1$PAOI)))) * (1.0 + (-2.0 * ($Pics_envelopecassette1$PglazingLossesOuter$PR_Fres / (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres)))))), 0.0, data->simulationInfo.storedRelations[3]);
  gout[3] = (tmp2840) ? 1 : -1;
  tmp2841 = LessEqZC($PG_DN, 1.0, data->simulationInfo.storedRelations[4]);
  gout[4] = (tmp2841) ? 1 : -1;
  tmp2842 = LessEqZC($Pics_context1$PAOI, 1.570795, data->simulationInfo.storedRelations[5]);
  gout[5] = (tmp2842) ? 1 : -1;
  tmp2843 = GreaterZC($Pics_context1$PDNI, 0.0, data->simulationInfo.storedRelations[6]);
  gout[6] = (tmp2843) ? 1 : -1;
  tmp2844 = GreaterZC(($Pics_context1$PweaDat$PconTim1$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim1$PtStart), 31536000.0, data->simulationInfo.storedRelations[7]);
  gout[7] = (tmp2844) ? 1 : -1;
  tmp2845 = GreaterZC(($Pics_context1$PweaDat$PconTim$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim$PtStart), 31536000.0, data->simulationInfo.storedRelations[8]);
  gout[8] = (tmp2845) ? 1 : -1;
  tmp2846 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[9]);
  gout[9] = (tmp2846) ? 1 : -1;
  tmp2847 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[10]);
  gout[10] = (tmp2847) ? 1 : -1;
  tmp2848 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[11]);
  gout[11] = (tmp2848) ? 1 : -1;
  tmp2849 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[12]);
  gout[12] = (tmp2849) ? 1 : -1;
  tmp2850 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[13]);
  gout[13] = (tmp2850) ? 1 : -1;
  tmp2851 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[14]);
  gout[14] = (tmp2851) ? 1 : -1;
  tmp2852 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[15]);
  gout[15] = (tmp2852) ? 1 : -1;
  tmp2853 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[16]);
  gout[16] = (tmp2853) ? 1 : -1;
  tmp2854 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[17]);
  gout[17] = (tmp2854) ? 1 : -1;
  tmp2855 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[18]);
  gout[18] = (tmp2855) ? 1 : -1;
  tmp2856 = GreaterEqZC(time, $P$PRE$PIC_Data_all$PnextTimeEvent, data->simulationInfo.storedRelations[19]);
  gout[19] = (tmp2856) ? 1 : -1;
  tmp2857 = 31536000.0;
  if (tmp2857 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_context1.weaDat.conTim1.simTim / 31536000.0");}
  gout[20] = (floor(($Pics_context1$PweaDat$PconTim1$PsimTim / 31536000.0)) != floor(data->simulationInfo.mathEventsValuePre[(modelica_integer) 0])) ? 1 : -1;
  tmp2858 = 31536000.0;
  if (tmp2858 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_context1.weaDat.conTim.simTim / 31536000.0");}
  gout[21] = (floor(($Pics_context1$PweaDat$PconTim$PsimTim / 31536000.0)) != floor(data->simulationInfo.mathEventsValuePre[(modelica_integer) 1])) ? 1 : -1;
  
  TRACE_POP
  return 0;
}

const char *ICSolar_ICS_Skeleton_relationDescription(int i)
{
  const char *res[] = {"time >= pre(T_cav_in.nextTimeEvent)",
  "abs(ics_envelopecassette1.Tubing[1].flowPort_b.H_flow) - ics_envelopecassette1.flowport_a.H_flow < 0.0",
  "ics_envelopecassette1.Power_Electric < 0.0",
  "(1.0 - ics_envelopecassette1.glazingLossesOuter.R_sfc / cos(ics_context1.AOI)) * (1.0 - ics_envelopecassette1.glazingLossesOuter.c_disp * 6.0 / cos(ics_context1.AOI)) * (1.0 + -2.0 * ics_envelopecassette1.glazingLossesOuter.R_Fres / (1.0 + ics_envelopecassette1.glazingLossesOuter.R_Fres)) < 0.0",
  "G_DN <= 1.0",
  "ics_context1.AOI <= 1.570795",
  "ics_context1.DNI > 0.0",
  "ics_context1.weaDat.conTim1.simTim - pre(ics_context1.weaDat.conTim1.tStart) > 31536000.0",
  "ics_context1.weaDat.conTim.simTim - pre(ics_context1.weaDat.conTim.tStart) > 31536000.0",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[1].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[2].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[3].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[4].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[5].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[6].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[7].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[8].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[9].eGen_on.nextTimeEvent)",
  "time >= pre(ics_envelopecassette1.ics_stack[1].ICS_Module_Twelve_1[10].eGen_on.nextTimeEvent)",
  "time >= pre(IC_Data_all.nextTimeEvent)"};
  return res[i];
}

int ICSolar_ICS_Skeleton_function_updateRelations(DATA *data, int evalforZeroCross)
{
  modelica_boolean tmp2859;
  modelica_boolean tmp2860;
  modelica_boolean tmp2861;
  modelica_real tmp2862;
  modelica_real tmp2863;
  modelica_real tmp2864;
  modelica_boolean tmp2865;
  modelica_boolean tmp2866;
  modelica_boolean tmp2867;
  modelica_boolean tmp2868;
  modelica_boolean tmp2869;
  modelica_boolean tmp2870;
  modelica_boolean tmp2871;
  modelica_boolean tmp2872;
  modelica_boolean tmp2873;
  modelica_boolean tmp2874;
  modelica_boolean tmp2875;
  modelica_boolean tmp2876;
  modelica_boolean tmp2877;
  modelica_boolean tmp2878;
  modelica_boolean tmp2879;
  modelica_boolean tmp2880;
  modelica_boolean tmp2881;
  modelica_real tmp2882;
  modelica_real tmp2883;
  modelica_real tmp2884;
  
  TRACE_PUSH
  
  if(evalforZeroCross)
  {
    tmp2859 = GreaterEqZC(time, $P$PRE$PT_cav_in$PnextTimeEvent, data->simulationInfo.storedRelations[0]);
    data->simulationInfo.relations[0] = tmp2859;
    tmp2860 = LessZC((fabs($Pics_envelopecassette1$PTubing$lB1$rB$PflowPort_b$PH_flow) - $Pics_envelopecassette1$Pflowport_a$PH_flow), 0.0, data->simulationInfo.storedRelations[1]);
    data->simulationInfo.relations[1] = tmp2860;
    tmp2861 = LessZC($Pics_envelopecassette1$PPower_Electric, 0.0, data->simulationInfo.storedRelations[2]);
    data->simulationInfo.relations[2] = tmp2861;
    tmp2862 = cos($Pics_context1$PAOI);
    if (tmp2862 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_sfc / cos(ics_context1.AOI)");}
    tmp2863 = cos($Pics_context1$PAOI);
    if (tmp2863 == 0) {throwStreamPrint(threadData, "Division by zero %s", "6.0 / cos(ics_context1.AOI)");}
    tmp2864 = (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres);
    if (tmp2864 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_Fres / (1.0 + ics_envelopecassette1.glazingLossesOuter.R_Fres)");}
    tmp2865 = LessZC(((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$PR_sfc / cos($Pics_context1$PAOI))) * ((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$Pc_disp * (6.0 / cos($Pics_context1$PAOI)))) * (1.0 + (-2.0 * ($Pics_envelopecassette1$PglazingLossesOuter$PR_Fres / (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres)))))), 0.0, data->simulationInfo.storedRelations[3]);
    data->simulationInfo.relations[3] = tmp2865;
    tmp2866 = LessEqZC($PG_DN, 1.0, data->simulationInfo.storedRelations[4]);
    data->simulationInfo.relations[4] = tmp2866;
    tmp2867 = LessEqZC($Pics_context1$PAOI, 1.570795, data->simulationInfo.storedRelations[5]);
    data->simulationInfo.relations[5] = tmp2867;
    tmp2868 = GreaterZC($Pics_context1$PDNI, 0.0, data->simulationInfo.storedRelations[6]);
    data->simulationInfo.relations[6] = tmp2868;
    tmp2869 = GreaterZC(($Pics_context1$PweaDat$PconTim1$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim1$PtStart), 31536000.0, data->simulationInfo.storedRelations[7]);
    data->simulationInfo.relations[7] = tmp2869;
    tmp2870 = GreaterZC(($Pics_context1$PweaDat$PconTim$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim$PtStart), 31536000.0, data->simulationInfo.storedRelations[8]);
    data->simulationInfo.relations[8] = tmp2870;
    tmp2871 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[9]);
    data->simulationInfo.relations[9] = tmp2871;
    tmp2872 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[10]);
    data->simulationInfo.relations[10] = tmp2872;
    tmp2873 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[11]);
    data->simulationInfo.relations[11] = tmp2873;
    tmp2874 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[12]);
    data->simulationInfo.relations[12] = tmp2874;
    tmp2875 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[13]);
    data->simulationInfo.relations[13] = tmp2875;
    tmp2876 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[14]);
    data->simulationInfo.relations[14] = tmp2876;
    tmp2877 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[15]);
    data->simulationInfo.relations[15] = tmp2877;
    tmp2878 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[16]);
    data->simulationInfo.relations[16] = tmp2878;
    tmp2879 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[17]);
    data->simulationInfo.relations[17] = tmp2879;
    tmp2880 = GreaterEqZC(time, $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent, data->simulationInfo.storedRelations[18]);
    data->simulationInfo.relations[18] = tmp2880;
    tmp2881 = GreaterEqZC(time, $P$PRE$PIC_Data_all$PnextTimeEvent, data->simulationInfo.storedRelations[19]);
    data->simulationInfo.relations[19] = tmp2881;
  }
  else
  {
    data->simulationInfo.relations[0] = (time >= $P$PRE$PT_cav_in$PnextTimeEvent);
    data->simulationInfo.relations[1] = ((fabs($Pics_envelopecassette1$PTubing$lB1$rB$PflowPort_b$PH_flow) - $Pics_envelopecassette1$Pflowport_a$PH_flow) < 0.0);
    data->simulationInfo.relations[2] = ($Pics_envelopecassette1$PPower_Electric < 0.0);
    tmp2882 = cos($Pics_context1$PAOI);
    if (tmp2882 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_sfc / cos(ics_context1.AOI)");}
    tmp2883 = cos($Pics_context1$PAOI);
    if (tmp2883 == 0) {throwStreamPrint(threadData, "Division by zero %s", "6.0 / cos(ics_context1.AOI)");}
    tmp2884 = (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres);
    if (tmp2884 == 0) {throwStreamPrint(threadData, "Division by zero %s", "ics_envelopecassette1.glazingLossesOuter.R_Fres / (1.0 + ics_envelopecassette1.glazingLossesOuter.R_Fres)");}
    data->simulationInfo.relations[3] = (((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$PR_sfc / cos($Pics_context1$PAOI))) * ((1.0 - ($Pics_envelopecassette1$PglazingLossesOuter$Pc_disp * (6.0 / cos($Pics_context1$PAOI)))) * (1.0 + (-2.0 * ($Pics_envelopecassette1$PglazingLossesOuter$PR_Fres / (1.0 + $Pics_envelopecassette1$PglazingLossesOuter$PR_Fres)))))) < 0.0);
    data->simulationInfo.relations[4] = ($PG_DN <= 1.0);
    data->simulationInfo.relations[5] = ($Pics_context1$PAOI <= 1.570795);
    data->simulationInfo.relations[6] = ($Pics_context1$PDNI > 0.0);
    data->simulationInfo.relations[7] = (($Pics_context1$PweaDat$PconTim1$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim1$PtStart) > 31536000.0);
    data->simulationInfo.relations[8] = (($Pics_context1$PweaDat$PconTim$PsimTim - $P$PRE$Pics_context1$PweaDat$PconTim$PtStart) > 31536000.0);
    data->simulationInfo.relations[9] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[10] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[11] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[12] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[13] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[14] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[15] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[16] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[17] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[18] = (time >= $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent);
    data->simulationInfo.relations[19] = (time >= $P$PRE$PIC_Data_all$PnextTimeEvent);
  }
  
  TRACE_POP
  return 0;
}

int ICSolar_ICS_Skeleton_checkForDiscreteChanges(DATA *data)
{
  int needToIterate = 0;

  TRACE_PUSH

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes at time=%.12g", data->localData[0]->timeValue);
  if($P$whenCondition14 != $P$PRE$P$whenCondition14)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition14 from %d to %d", $P$PRE$P$whenCondition14, $P$whenCondition14);
    needToIterate = 1;
  }
  if($PIC_Data_all$PnextTimeEvent != $P$PRE$PIC_Data_all$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: IC_Data_all._nextTimeEvent from %g to %g", $P$PRE$PIC_Data_all$PnextTimeEvent, $PIC_Data_all$PnextTimeEvent);
    needToIterate = 1;
  }
  if($P$whenCondition13 != $P$PRE$P$whenCondition13)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition13 from %d to %d", $P$PRE$P$whenCondition13, $P$whenCondition13);
    needToIterate = 1;
  }
  if($P$whenCondition12 != $P$PRE$P$whenCondition12)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition12 from %d to %d", $P$PRE$P$whenCondition12, $P$whenCondition12);
    needToIterate = 1;
  }
  if($P$whenCondition11 != $P$PRE$P$whenCondition11)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition11 from %d to %d", $P$PRE$P$whenCondition11, $P$whenCondition11);
    needToIterate = 1;
  }
  if($P$whenCondition10 != $P$PRE$P$whenCondition10)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition10 from %d to %d", $P$PRE$P$whenCondition10, $P$whenCondition10);
    needToIterate = 1;
  }
  if($P$whenCondition9 != $P$PRE$P$whenCondition9)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition9 from %d to %d", $P$PRE$P$whenCondition9, $P$whenCondition9);
    needToIterate = 1;
  }
  if($P$whenCondition8 != $P$PRE$P$whenCondition8)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition8 from %d to %d", $P$PRE$P$whenCondition8, $P$whenCondition8);
    needToIterate = 1;
  }
  if($P$whenCondition7 != $P$PRE$P$whenCondition7)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition7 from %d to %d", $P$PRE$P$whenCondition7, $P$whenCondition7);
    needToIterate = 1;
  }
  if($P$whenCondition6 != $P$PRE$P$whenCondition6)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition6 from %d to %d", $P$PRE$P$whenCondition6, $P$whenCondition6);
    needToIterate = 1;
  }
  if($P$whenCondition5 != $P$PRE$P$whenCondition5)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition5 from %d to %d", $P$PRE$P$whenCondition5, $P$whenCondition5);
    needToIterate = 1;
  }
  if($P$whenCondition4 != $P$PRE$P$whenCondition4)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition4 from %d to %d", $P$PRE$P$whenCondition4, $P$whenCondition4);
    needToIterate = 1;
  }
  if($P$whenCondition3 != $P$PRE$P$whenCondition3)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition3 from %d to %d", $P$PRE$P$whenCondition3, $P$whenCondition3);
    needToIterate = 1;
  }
  if($P$whenCondition2 != $P$PRE$P$whenCondition2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition2 from %d to %d", $P$PRE$P$whenCondition2, $P$whenCondition2);
    needToIterate = 1;
  }
  if($Pics_context1$PweaDat$PconTim1$PtStart != $P$PRE$Pics_context1$PweaDat$PconTim1$PtStart)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_context1._weaDat._conTim1._tStart from %g to %g", $P$PRE$Pics_context1$PweaDat$PconTim1$PtStart, $Pics_context1$PweaDat$PconTim1$PtStart);
    needToIterate = 1;
  }
  if($Pics_context1$PweaDat$PconTim$PtStart != $P$PRE$Pics_context1$PweaDat$PconTim$PtStart)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_context1._weaDat._conTim._tStart from %g to %g", $P$PRE$Pics_context1$PweaDat$PconTim$PtStart, $Pics_context1$PweaDat$PconTim$PtStart);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[1]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[1]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[1]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[2]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[2]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[2]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[3]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[3]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[3]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[4]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[4]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[4]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[5]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[5]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[5]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[6]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[6]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[6]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[7]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[7]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[7]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[8]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[8]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[8]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[9]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[9]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[9]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[10]._choosefractexposedlutposition1._FractExposedTypeCol from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeCol);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[10]._choosefractexposedlutposition1._FractExposedTypeRow from %ld to %ld", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pchoosefractexposedlutposition1$PFractExposedTypeRow);
    needToIterate = 1;
  }
  if($Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent != $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: ics_envelopecassette1._ics_stack[1]._ICS_Module_Twelve_1[10]._eGen_on._nextTimeEvent from %g to %g", $P$PRE$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent, $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PnextTimeEvent);
    needToIterate = 1;
  }
  if($P$whenCondition1 != $P$PRE$P$whenCondition1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition1 from %d to %d", $P$PRE$P$whenCondition1, $P$whenCondition1);
    needToIterate = 1;
  }
  if($PT_cav_in$PnextTimeEvent != $P$PRE$PT_cav_in$PnextTimeEvent)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: T_cav_in._nextTimeEvent from %g to %g", $P$PRE$PT_cav_in$PnextTimeEvent, $PT_cav_in$PnextTimeEvent);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  TRACE_POP
  return needToIterate;
}

#if defined(__cplusplus)
}
#endif

