/* External objects file */
/* Simulation code for ICSolar.ICS_Skeleton generated by the OpenModelica Compiler 1.9.1 (r22929) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "ICSolar.ICS_Skeleton_functions.h"
#include "ICSolar.ICS_Skeleton_model.h"
#include "ICSolar.ICS_Skeleton_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

/* Has to be performed after _init.xml file has been read */
void ICSolar_ICS_Skeleton_callExternalObjectConstructors(DATA *data)
{
  real_array tmp2292;
  integer_array tmp2293;
  real_array tmp2294;
  integer_array tmp2295;
  real_array tmp2296;
  integer_array tmp2297;
  real_array tmp2298;
  integer_array tmp2299;
  real_array tmp2300;
  integer_array tmp2301;
  real_array tmp2302;
  integer_array tmp2303;
  real_array tmp2304;
  integer_array tmp2305;
  real_array tmp2306;
  integer_array tmp2307;
  real_array tmp2308;
  integer_array tmp2309;
  real_array tmp2310;
  integer_array tmp2311;
  real_array tmp2312;
  integer_array tmp2313;
  real_array tmp2314;
  integer_array tmp2315;
  real_array tmp2316;
  integer_array tmp2317;
  real_array tmp2318;
  integer_array tmp2319;
  real_array tmp2320;
  integer_array tmp2321;
  real_array tmp2322;
  integer_array tmp2323;
  real_array tmp2324;
  integer_array tmp2325;
  real_array tmp2326;
  integer_array tmp2327;
  real_array tmp2328;
  integer_array tmp2329;
  real_array tmp2330;
  integer_array tmp2331;
  real_array tmp2332;
  integer_array tmp2333;
  real_array tmp2334;
  integer_array tmp2335;
  real_array tmp2336;
  integer_array tmp2337;
  real_array tmp2338;
  integer_array tmp2339;
  /* data->simulationInfo.extObjs = NULL; */
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors");
  alloc_real_array(&tmp2292, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2293, 1, (modelica_integer)(modelica_integer) 2);
  $PT_cav_in$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "T_Cav", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\20150323\\T_Cav_data.txt", tmp2292, 0.0, tmp2293, 1, 2);
  alloc_real_array(&tmp2294, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2295, 25, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13, (modelica_integer)(modelica_integer) 14, (modelica_integer)(modelica_integer) 15, (modelica_integer)(modelica_integer) 16, (modelica_integer)(modelica_integer) 17, (modelica_integer)(modelica_integer) 18, (modelica_integer)(modelica_integer) 19, (modelica_integer)(modelica_integer) 20, (modelica_integer)(modelica_integer) 21, (modelica_integer)(modelica_integer) 22, (modelica_integer)(modelica_integer) 23, (modelica_integer)(modelica_integer) 24, (modelica_integer)(modelica_integer) 25, (modelica_integer)(modelica_integer) 26, (modelica_integer)(modelica_integer) 27, (modelica_integer)(modelica_integer) 28, (modelica_integer)(modelica_integer) 29, (modelica_integer)(modelica_integer) 30);
  $Pics_context1$PweaDat$PdatRea$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "tab1", "C:/Users/Justin/Documents/GitHub/RPI_CASE_ICS_Modelica/weatherdata/USA_NY_New.York-Central.Park.725033_TMY3.mos", tmp2294, tmp2295, 2);
  alloc_real_array(&tmp2296, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2297, 4, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11);
  $Pics_context1$PweaDat$PdatRea1$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "tab1", "C:/Users/Justin/Documents/GitHub/RPI_CASE_ICS_Modelica/weatherdata/USA_NY_New.York-Central.Park.725033_TMY3.mos", tmp2296, tmp2297, 2);
  alloc_real_array(&tmp2298, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2299, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2298, tmp2299, 1);
  alloc_real_array(&tmp2300, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2301, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2300, 0.0, tmp2301, 3, 1);
  alloc_real_array(&tmp2302, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2303, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2302, tmp2303, 1);
  alloc_real_array(&tmp2304, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2305, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2304, 0.0, tmp2305, 3, 1);
  alloc_real_array(&tmp2306, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2307, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2306, tmp2307, 1);
  alloc_real_array(&tmp2308, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2309, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2308, 0.0, tmp2309, 3, 1);
  alloc_real_array(&tmp2310, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2311, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2310, tmp2311, 1);
  alloc_real_array(&tmp2312, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2313, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2312, 0.0, tmp2313, 3, 1);
  alloc_real_array(&tmp2314, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2315, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2314, tmp2315, 1);
  alloc_real_array(&tmp2316, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2317, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2316, 0.0, tmp2317, 3, 1);
  alloc_real_array(&tmp2318, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2319, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2318, tmp2319, 1);
  alloc_real_array(&tmp2320, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2321, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2320, 0.0, tmp2321, 3, 1);
  alloc_real_array(&tmp2322, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2323, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2322, tmp2323, 1);
  alloc_real_array(&tmp2324, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2325, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2324, 0.0, tmp2325, 3, 1);
  alloc_real_array(&tmp2326, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2327, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2326, tmp2327, 1);
  alloc_real_array(&tmp2328, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2329, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2328, 0.0, tmp2329, 3, 1);
  alloc_real_array(&tmp2330, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2331, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2330, tmp2331, 1);
  alloc_real_array(&tmp2332, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2333, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2332, 0.0, tmp2333, 3, 1);
  alloc_real_array(&tmp2334, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2335, 1, (modelica_integer)(modelica_integer) 2);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pshadingfraction_function1$PLUT$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData, "4DLUT", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\4D_LUT\\4DLUT.txt", tmp2334, tmp2335, 1);
  alloc_real_array(&tmp2336, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2337, 12, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13);
  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "EgenIO", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\EgenIO.txt", tmp2336, 0.0, tmp2337, 3, 1);
  alloc_real_array(&tmp2338, 2, 0, 1);
  array_alloc_scalar_integer_array(&tmp2339, 24, (modelica_integer)(modelica_integer) 2, (modelica_integer)(modelica_integer) 3, (modelica_integer)(modelica_integer) 4, (modelica_integer)(modelica_integer) 5, (modelica_integer)(modelica_integer) 6, (modelica_integer)(modelica_integer) 7, (modelica_integer)(modelica_integer) 8, (modelica_integer)(modelica_integer) 9, (modelica_integer)(modelica_integer) 10, (modelica_integer)(modelica_integer) 11, (modelica_integer)(modelica_integer) 12, (modelica_integer)(modelica_integer) 13, (modelica_integer)(modelica_integer) 14, (modelica_integer)(modelica_integer) 15, (modelica_integer)(modelica_integer) 16, (modelica_integer)(modelica_integer) 17, (modelica_integer)(modelica_integer) 18, (modelica_integer)(modelica_integer) 19, (modelica_integer)(modelica_integer) 20, (modelica_integer)(modelica_integer) 21, (modelica_integer)(modelica_integer) 22, (modelica_integer)(modelica_integer) 23, (modelica_integer)(modelica_integer) 24, (modelica_integer)(modelica_integer) 25);
  $PIC_Data_all$PtableID = omc_Modelica_Blocks_Types_ExternalCombiTimeTable_constructor(threadData, "DNI_THTFin_vdot", "C:\\Users\\Justin\\Documents\\GitHub\\RPI_CASE_ICS_Modelica\\20150323\\measuredData20150323r1.txt", tmp2338, 0.0, tmp2339, 1, 2);
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors finished");
}

void ICSolar_ICS_Skeleton_callExternalObjectDestructors(DATA *data)
{
  if(data->simulationInfo.extObjs)
  {
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$PT_cav_in$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_context1$PweaDat$PdatRea$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_context1$PweaDat$PdatRea1$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pshadingfraction_function1$PLUT$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$PeGen_on$PtableID);
    omc_Modelica_Blocks_Types_ExternalCombiTimeTable_destructor(threadData,$PIC_Data_all$PtableID);
    free(data->simulationInfo.extObjs);
    data->simulationInfo.extObjs = 0;
  }
}
#if defined(__cplusplus)
}
#endif

