function createfigure(YMatrix1, YMatrix2)
%CREATEFIGURE(YMATRIX1, YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 29-May-2015 17:22:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'OuterPosition',[0 0.5 1 0.5]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[90.0228501153731 118.411729338436]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[32.3631625489985 44.6983819686977]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'Color',[0 0 1],'DisplayName','measured_Egen');
set(plot1(2),'LineStyle',':','Color',[0 0 1],...
    'DisplayName','UQ_measured_Egen_upper');
set(plot1(3),'LineStyle',':','DisplayName','UQ_measured_Egen_lower');
set(plot1(4),'Visible','off','DisplayName','temp_flowport_b');
set(plot1(5),'Visible','off','Color',[1 0 0],'DisplayName','Q_arrayTotal');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');

% Create axes
axes2 = axes('Parent',figure1,'OuterPosition',[0 0 1 0.5]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[89.7986217523803 116.728684939998]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[338.285071217415 364.57034399355]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',axes2,'Color',[1 0 0],'LineStyle',':');
set(plot2(1),'DisplayName','measured_T_HTFout','LineStyle','-');
set(plot2(2),'DisplayName','UQ_measured_T_HTFout_lower');
set(plot2(3),'DisplayName','UQ_measured_T_HTFout_upper');

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'Location','SouthEast');

