/* Linear Systems */
/* Simulation code for ICSolar.ICS_Skeleton generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "ICSolar.ICS_Skeleton_functions.h"
#include "ICSolar.ICS_Skeleton_model.h"
#include "ICSolar.ICS_Skeleton_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "ICSolar.ICS_Skeleton_12jac.h"

/* initial linear systems */
void setLinearMatrixA570(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,570};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, -1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb570(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,570};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA583(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,583};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, -1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb583(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,583};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA602(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,602};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 1, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 5, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 6, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 6, 1.0, 17, linearSystemData);
}
void setLinearVectorb602(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,602};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA608(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,608};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb608(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,608};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA627(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,627};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 1, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 5, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 6, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 6, 1.0, 17, linearSystemData);
}
void setLinearVectorb627(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,627};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA633(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,633};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb633(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,633};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA652(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,652};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 2, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 1, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, -1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 4, 1.0, 17, linearSystemData);
}
void setLinearVectorb652(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,652};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA658(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,658};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb658(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,658};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA677(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,677};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 1, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 7, linearSystemData);
  linearSystemData->setAElement(3, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 8, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 5, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 5, 1.0, 17, linearSystemData);
}
void setLinearVectorb677(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,677};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA683(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,683};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb683(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,683};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA702(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,702};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 1, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 7, linearSystemData);
  linearSystemData->setAElement(3, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 8, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 5, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 5, 1.0, 17, linearSystemData);
}
void setLinearVectorb702(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,702};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA708(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,708};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb708(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,708};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA727(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,727};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 2, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 1, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, -1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 4, 1.0, 17, linearSystemData);
}
void setLinearVectorb727(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,727};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA733(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,733};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb733(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,733};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA752(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,752};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 1, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 5, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 6, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 6, 1.0, 17, linearSystemData);
}
void setLinearVectorb752(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,752};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA758(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,758};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb758(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,758};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA777(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,777};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 2, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 1, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, -1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 4, 1.0, 17, linearSystemData);
}
void setLinearVectorb777(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,777};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA783(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,783};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, -1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb783(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,783};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[1] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA802(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,802};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 1, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 5, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 6, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, -1.0, 14, linearSystemData);
  linearSystemData->setAElement(6, 2, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 6, 1.0, 17, linearSystemData);
}
void setLinearVectorb802(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,802};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  0.0;
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA815(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,815};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 1, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 0, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, -1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 16, linearSystemData);
  linearSystemData->setAElement(7, 4, 1.0, 17, linearSystemData);
}
void setLinearVectorb815(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,815};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}
/* inline linear systems */
/* parameter linear systems */
/* model linear systems */
void setLinearMatrixA3788(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3788};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb3788(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3788};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA3815(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3815};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 4, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 6, -1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 3, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 2, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 6, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(5, 0, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 6, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb3815(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3815};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB10$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA3832(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3832};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb3832(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3832};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA3859(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3859};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 2, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 0, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 4, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb3859(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3859};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB9$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA3876(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3876};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb3876(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3876};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA3903(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3903};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 2, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 0, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 4, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 4, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb3903(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3903};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB8$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA3920(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3920};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb3920(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3920};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA3947(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3947};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 2, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 6, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 5, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 5, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb3947(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3947};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB7$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA3964(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3964};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb3964(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3964};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}

void setLinearMatrixA3991(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3991};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 4, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 6, -1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 3, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 2, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 6, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(5, 0, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 6, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb3991(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,3991};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB6$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA4008(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4008};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb4008(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4008};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA4035(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4035};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 4, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 6, -1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 3, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 2, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 6, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(5, 0, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 6, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb4035(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4035};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB5$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA4052(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4052};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb4052(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4052};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA4079(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4079};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, -1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 14, linearSystemData);
  linearSystemData->setAElement(6, 3, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 16, linearSystemData);
  linearSystemData->setAElement(7, 3, -1.0, 17, linearSystemData);
}
void setLinearVectorb4079(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4079};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB4$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA4096(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4096};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb4096(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4096};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA4123(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4123};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(2, 6, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 4, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(3, 5, -1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 14, linearSystemData);
  linearSystemData->setAElement(6, 3, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 16, linearSystemData);
  linearSystemData->setAElement(7, 3, -1.0, 17, linearSystemData);
}
void setLinearVectorb4123(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4123};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB3$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  0.0;

}

void setLinearMatrixA4140(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4140};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 3, linearSystemData);
  linearSystemData->setAElement(2, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 2, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 0, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb4140(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4140};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;

}

void setLinearMatrixA4178(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4178};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 2, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 6, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(1, 7, -1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 5, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(2, 6, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 6, linearSystemData);
  linearSystemData->setAElement(3, 4, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 0, 1.0, 9, linearSystemData);
  linearSystemData->setAElement(4, 3, -1.0, 10, linearSystemData);
  linearSystemData->setAElement(4, 4, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 12, linearSystemData);
  linearSystemData->setAElement(5, 5, -1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 5, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb4178(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4178};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB2$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA4186(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4186};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 4, -1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 7, 1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 6, -1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 7, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_WaterTube), 3, linearSystemData);
  linearSystemData->setAElement(2, 5, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Tube$PG), 4, linearSystemData);
  linearSystemData->setAElement(2, 6, 1.0, 5, linearSystemData);
  linearSystemData->setAElement(3, 2, 1.0, 6, linearSystemData);
  linearSystemData->setAElement(3, 4, -1.0, 7, linearSystemData);
  linearSystemData->setAElement(3, 5, 1.0, 8, linearSystemData);
  linearSystemData->setAElement(4, 3, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConduction_Insulation$PG), 9, linearSystemData);
  linearSystemData->setAElement(4, 6, 1.0, 10, linearSystemData);
  linearSystemData->setAElement(5, 0, 1.0, 11, linearSystemData);
  linearSystemData->setAElement(5, 2, -1.0, 12, linearSystemData);
  linearSystemData->setAElement(5, 3, 1.0, 13, linearSystemData);
  linearSystemData->setAElement(6, 1, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PConv_InsulationAir), 14, linearSystemData);
  linearSystemData->setAElement(6, 6, 1.0, 15, linearSystemData);
  linearSystemData->setAElement(7, 0, -1.0, 16, linearSystemData);
  linearSystemData->setAElement(7, 1, 1.0, 17, linearSystemData);
}
void setLinearVectorb4186(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4186};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Ptubing_Losses1$PTubing$PheatPort$PT);
  linearSystemData->b[1] =  0.0;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;
  linearSystemData->b[4] =  0.0;
  linearSystemData->b[5] =  0.0;
  linearSystemData->b[6] =  0.0;
  linearSystemData->b[7] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);

}

void setLinearMatrixA4220(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4220};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, 1.0, 0, linearSystemData);
  linearSystemData->setAElement(0, 3, -1.0, 1, linearSystemData);
  linearSystemData->setAElement(1, 2, 1.0, 2, linearSystemData);
  linearSystemData->setAElement(1, 3, 1.0, 3, linearSystemData);
  linearSystemData->setAElement(2, 1, 1.0, 4, linearSystemData);
  linearSystemData->setAElement(2, 2, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Pwater_Block_HX1$Pthermalconductor1$PG), 5, linearSystemData);
  linearSystemData->setAElement(3, 0, (-$Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$Pwater_Block_HX1$PConv_Receiver), 6, linearSystemData);
  linearSystemData->setAElement(3, 1, 1.0, 7, linearSystemData);
}
void setLinearVectorb4220(void *inData, void *systemData)
{
  const int equationIndexes[2] = {1,4220};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$Pics_envelopecassette1$Pcavityheatbalance1$PCavityHeatCapacity$PT);
  linearSystemData->b[1] =  $Pics_envelopecassette1$Pics_stack$lB1$rB$PICS_Module_Twelve_1$lB1$rB$Pmodulereceiver1$PreceiverInternalEnergy1$Pheatcapacitor1$PT;
  linearSystemData->b[2] =  0.0;
  linearSystemData->b[3] =  0.0;

}
/* jacobians linear systems */

/* funtion initialize linear systems */
void ICSolar_ICS_Skeleton_initialLinearSystem(LINEAR_SYSTEM_DATA* linearSystemData)
{
  /* initial linear systems */
  linearSystemData[0].equationIndex = 570;
  linearSystemData[0].size = 4;
  linearSystemData[0].nnz = 8;
  linearSystemData[0].setA = setLinearMatrixA570;
  linearSystemData[0].setb = setLinearVectorb570;
  
  linearSystemData[1].equationIndex = 583;
  linearSystemData[1].size = 4;
  linearSystemData[1].nnz = 8;
  linearSystemData[1].setA = setLinearMatrixA583;
  linearSystemData[1].setb = setLinearVectorb583;
  
  linearSystemData[2].equationIndex = 602;
  linearSystemData[2].size = 8;
  linearSystemData[2].nnz = 18;
  linearSystemData[2].setA = setLinearMatrixA602;
  linearSystemData[2].setb = setLinearVectorb602;
  
  linearSystemData[3].equationIndex = 608;
  linearSystemData[3].size = 4;
  linearSystemData[3].nnz = 8;
  linearSystemData[3].setA = setLinearMatrixA608;
  linearSystemData[3].setb = setLinearVectorb608;
  
  linearSystemData[4].equationIndex = 627;
  linearSystemData[4].size = 8;
  linearSystemData[4].nnz = 18;
  linearSystemData[4].setA = setLinearMatrixA627;
  linearSystemData[4].setb = setLinearVectorb627;
  
  linearSystemData[5].equationIndex = 633;
  linearSystemData[5].size = 4;
  linearSystemData[5].nnz = 8;
  linearSystemData[5].setA = setLinearMatrixA633;
  linearSystemData[5].setb = setLinearVectorb633;
  
  linearSystemData[6].equationIndex = 652;
  linearSystemData[6].size = 8;
  linearSystemData[6].nnz = 18;
  linearSystemData[6].setA = setLinearMatrixA652;
  linearSystemData[6].setb = setLinearVectorb652;
  
  linearSystemData[7].equationIndex = 658;
  linearSystemData[7].size = 4;
  linearSystemData[7].nnz = 8;
  linearSystemData[7].setA = setLinearMatrixA658;
  linearSystemData[7].setb = setLinearVectorb658;
  
  linearSystemData[8].equationIndex = 677;
  linearSystemData[8].size = 8;
  linearSystemData[8].nnz = 18;
  linearSystemData[8].setA = setLinearMatrixA677;
  linearSystemData[8].setb = setLinearVectorb677;
  
  linearSystemData[9].equationIndex = 683;
  linearSystemData[9].size = 4;
  linearSystemData[9].nnz = 8;
  linearSystemData[9].setA = setLinearMatrixA683;
  linearSystemData[9].setb = setLinearVectorb683;
  
  linearSystemData[10].equationIndex = 702;
  linearSystemData[10].size = 8;
  linearSystemData[10].nnz = 18;
  linearSystemData[10].setA = setLinearMatrixA702;
  linearSystemData[10].setb = setLinearVectorb702;
  
  linearSystemData[11].equationIndex = 708;
  linearSystemData[11].size = 4;
  linearSystemData[11].nnz = 8;
  linearSystemData[11].setA = setLinearMatrixA708;
  linearSystemData[11].setb = setLinearVectorb708;
  
  linearSystemData[12].equationIndex = 727;
  linearSystemData[12].size = 8;
  linearSystemData[12].nnz = 18;
  linearSystemData[12].setA = setLinearMatrixA727;
  linearSystemData[12].setb = setLinearVectorb727;
  
  linearSystemData[13].equationIndex = 733;
  linearSystemData[13].size = 4;
  linearSystemData[13].nnz = 8;
  linearSystemData[13].setA = setLinearMatrixA733;
  linearSystemData[13].setb = setLinearVectorb733;
  
  linearSystemData[14].equationIndex = 752;
  linearSystemData[14].size = 8;
  linearSystemData[14].nnz = 18;
  linearSystemData[14].setA = setLinearMatrixA752;
  linearSystemData[14].setb = setLinearVectorb752;
  
  linearSystemData[15].equationIndex = 758;
  linearSystemData[15].size = 4;
  linearSystemData[15].nnz = 8;
  linearSystemData[15].setA = setLinearMatrixA758;
  linearSystemData[15].setb = setLinearVectorb758;
  
  linearSystemData[16].equationIndex = 777;
  linearSystemData[16].size = 8;
  linearSystemData[16].nnz = 18;
  linearSystemData[16].setA = setLinearMatrixA777;
  linearSystemData[16].setb = setLinearVectorb777;
  
  linearSystemData[17].equationIndex = 783;
  linearSystemData[17].size = 4;
  linearSystemData[17].nnz = 8;
  linearSystemData[17].setA = setLinearMatrixA783;
  linearSystemData[17].setb = setLinearVectorb783;
  
  linearSystemData[18].equationIndex = 802;
  linearSystemData[18].size = 8;
  linearSystemData[18].nnz = 18;
  linearSystemData[18].setA = setLinearMatrixA802;
  linearSystemData[18].setb = setLinearVectorb802;
  
  linearSystemData[19].equationIndex = 815;
  linearSystemData[19].size = 8;
  linearSystemData[19].nnz = 18;
  linearSystemData[19].setA = setLinearMatrixA815;
  linearSystemData[19].setb = setLinearVectorb815;
  /* inline linear systems */
  /* parameter linear systems */
  /* model linear systems */
  linearSystemData[20].equationIndex = 3788;
  linearSystemData[20].size = 4;
  linearSystemData[20].nnz = 8;
  linearSystemData[20].setA = setLinearMatrixA3788;
  linearSystemData[20].setb = setLinearVectorb3788;
  
  linearSystemData[21].equationIndex = 3815;
  linearSystemData[21].size = 8;
  linearSystemData[21].nnz = 18;
  linearSystemData[21].setA = setLinearMatrixA3815;
  linearSystemData[21].setb = setLinearVectorb3815;
  
  linearSystemData[22].equationIndex = 3832;
  linearSystemData[22].size = 4;
  linearSystemData[22].nnz = 8;
  linearSystemData[22].setA = setLinearMatrixA3832;
  linearSystemData[22].setb = setLinearVectorb3832;
  
  linearSystemData[23].equationIndex = 3859;
  linearSystemData[23].size = 8;
  linearSystemData[23].nnz = 18;
  linearSystemData[23].setA = setLinearMatrixA3859;
  linearSystemData[23].setb = setLinearVectorb3859;
  
  linearSystemData[24].equationIndex = 3876;
  linearSystemData[24].size = 4;
  linearSystemData[24].nnz = 8;
  linearSystemData[24].setA = setLinearMatrixA3876;
  linearSystemData[24].setb = setLinearVectorb3876;
  
  linearSystemData[25].equationIndex = 3903;
  linearSystemData[25].size = 8;
  linearSystemData[25].nnz = 18;
  linearSystemData[25].setA = setLinearMatrixA3903;
  linearSystemData[25].setb = setLinearVectorb3903;
  
  linearSystemData[26].equationIndex = 3920;
  linearSystemData[26].size = 4;
  linearSystemData[26].nnz = 8;
  linearSystemData[26].setA = setLinearMatrixA3920;
  linearSystemData[26].setb = setLinearVectorb3920;
  
  linearSystemData[27].equationIndex = 3947;
  linearSystemData[27].size = 8;
  linearSystemData[27].nnz = 18;
  linearSystemData[27].setA = setLinearMatrixA3947;
  linearSystemData[27].setb = setLinearVectorb3947;
  
  linearSystemData[28].equationIndex = 3964;
  linearSystemData[28].size = 4;
  linearSystemData[28].nnz = 8;
  linearSystemData[28].setA = setLinearMatrixA3964;
  linearSystemData[28].setb = setLinearVectorb3964;
  
  linearSystemData[29].equationIndex = 3991;
  linearSystemData[29].size = 8;
  linearSystemData[29].nnz = 18;
  linearSystemData[29].setA = setLinearMatrixA3991;
  linearSystemData[29].setb = setLinearVectorb3991;
  
  linearSystemData[30].equationIndex = 4008;
  linearSystemData[30].size = 4;
  linearSystemData[30].nnz = 8;
  linearSystemData[30].setA = setLinearMatrixA4008;
  linearSystemData[30].setb = setLinearVectorb4008;
  
  linearSystemData[31].equationIndex = 4035;
  linearSystemData[31].size = 8;
  linearSystemData[31].nnz = 18;
  linearSystemData[31].setA = setLinearMatrixA4035;
  linearSystemData[31].setb = setLinearVectorb4035;
  
  linearSystemData[32].equationIndex = 4052;
  linearSystemData[32].size = 4;
  linearSystemData[32].nnz = 8;
  linearSystemData[32].setA = setLinearMatrixA4052;
  linearSystemData[32].setb = setLinearVectorb4052;
  
  linearSystemData[33].equationIndex = 4079;
  linearSystemData[33].size = 8;
  linearSystemData[33].nnz = 18;
  linearSystemData[33].setA = setLinearMatrixA4079;
  linearSystemData[33].setb = setLinearVectorb4079;
  
  linearSystemData[34].equationIndex = 4096;
  linearSystemData[34].size = 4;
  linearSystemData[34].nnz = 8;
  linearSystemData[34].setA = setLinearMatrixA4096;
  linearSystemData[34].setb = setLinearVectorb4096;
  
  linearSystemData[35].equationIndex = 4123;
  linearSystemData[35].size = 8;
  linearSystemData[35].nnz = 18;
  linearSystemData[35].setA = setLinearMatrixA4123;
  linearSystemData[35].setb = setLinearVectorb4123;
  
  linearSystemData[36].equationIndex = 4140;
  linearSystemData[36].size = 4;
  linearSystemData[36].nnz = 8;
  linearSystemData[36].setA = setLinearMatrixA4140;
  linearSystemData[36].setb = setLinearVectorb4140;
  
  linearSystemData[37].equationIndex = 4178;
  linearSystemData[37].size = 8;
  linearSystemData[37].nnz = 18;
  linearSystemData[37].setA = setLinearMatrixA4178;
  linearSystemData[37].setb = setLinearVectorb4178;
  
  linearSystemData[38].equationIndex = 4186;
  linearSystemData[38].size = 8;
  linearSystemData[38].nnz = 18;
  linearSystemData[38].setA = setLinearMatrixA4186;
  linearSystemData[38].setb = setLinearVectorb4186;
  
  linearSystemData[39].equationIndex = 4220;
  linearSystemData[39].size = 4;
  linearSystemData[39].nnz = 8;
  linearSystemData[39].setA = setLinearMatrixA4220;
  linearSystemData[39].setb = setLinearVectorb4220;
  /* jacobians linear systems */
}


